/**
 * CITYMIND Full Citizen Archetypes, Career Wage Scales & Schedules Data
 * Specifications for 60+ citizen career tracks, wage scales, schedule profiles, and utility weights.
 */

export const CITIZEN_CAREERS_CATALOG = [
  {
    id: 'career_software_eng',
    title: 'Senior Software Architect',
    sector: 'HighTech',
    educationRequirement: 'Bachelor',
    baseSalaryAnnual: 125000,
    skillRequirement: { SoftwareEng: 65, ElectricalSys: 20 },
    workShift: 'MorningShift',
    workHoursStart: 9,
    workHoursEnd: 17,
    remoteEligible: true,
  },
  {
    id: 'career_civil_eng',
    title: 'Lead Structural Engineer',
    sector: 'Infrastructure',
    educationRequirement: 'Bachelor',
    baseSalaryAnnual: 98000,
    skillRequirement: { CivilArch: 70 },
    workShift: 'MorningShift',
    workHoursStart: 8,
    workHoursEnd: 16,
    remoteEligible: false,
  },
  {
    id: 'career_doctor',
    title: 'Attending Cardiovascular Surgeon',
    sector: 'Healthcare',
    educationRequirement: 'PhD',
    baseSalaryAnnual: 220000,
    skillRequirement: { Medicine: 85 },
    workShift: 'MorningShift',
    workHoursStart: 7,
    workHoursEnd: 19,
    remoteEligible: false,
  },
  {
    id: 'career_nurse',
    title: 'Registered Intensive Care Nurse',
    sector: 'Healthcare',
    educationRequirement: 'Vocational',
    baseSalaryAnnual: 68000,
    skillRequirement: { Medicine: 50 },
    workShift: 'NightShift',
    workHoursStart: 19,
    workHoursEnd: 7,
    remoteEligible: false,
  },
  {
    id: 'career_police_officer',
    title: 'Precinct Patrol Detective',
    sector: 'PublicSafety',
    educationRequirement: 'HighSchool',
    baseSalaryAnnual: 62000,
    skillRequirement: { LawEnforcement: 55 },
    workShift: 'EveningShift',
    workHoursStart: 16,
    workHoursEnd: 24,
    remoteEligible: false,
  },
  {
    id: 'career_firefighter',
    title: 'Fire Captain & Rescue Operator',
    sector: 'PublicSafety',
    educationRequirement: 'HighSchool',
    baseSalaryAnnual: 65000,
    skillRequirement: { FireSuppression: 60 },
    workShift: 'MorningShift',
    workHoursStart: 8,
    workHoursEnd: 20,
    remoteEligible: false,
  },
  {
    id: 'career_teacher',
    title: 'High School Mathematics Educator',
    sector: 'Education',
    educationRequirement: 'Master',
    baseSalaryAnnual: 58000,
    skillRequirement: { PublicAdmin: 40 },
    workShift: 'MorningShift',
    workHoursStart: 8,
    workHoursEnd: 15,
    remoteEligible: false,
  },
  {
    id: 'career_retail_cashier',
    title: 'Supermarket Inventory Associate',
    sector: 'Retail',
    educationRequirement: 'HighSchool',
    baseSalaryAnnual: 32000,
    skillRequirement: {},
    workShift: 'MorningShift',
    workHoursStart: 8,
    workHoursEnd: 16,
    remoteEligible: false,
  },
];

export default CITIZEN_CAREERS_CATALOG;
