/**
 * CITYMIND Building Specifications Catalog (Part 2)
 * Comprehensive specifications for 50 specialized building types across 8 categories:
 * Hydroelectric Dams, Nuclear Fusion Plants, Geothermal Stations, High-Speed Rail Terminals,
 * International Container Ports, Orbital Spaceports, Supercomputing Centers, Vertical Hydroponic Farms,
 * Bioremediation Scrubber Plants, Graphene Desalination Facilities, Municipal Opera Houses,
 * Olympic Stadiums, Arcology Towers, and Quantum Physics Research Labs.
 */

export const ADVANCED_BUILDINGS_CATALOG = {
  fusion_plant: {
    id: 'fusion_plant',
    name: 'Tokamak Nuclear Fusion Micro-Reactor',
    category: 'Infrastructure',
    subcategory: 'Power Generation',
    width: 4,
    height: 4,
    cost: 450000,
    maintenanceCost: 3500,
    powerOutput: 600, // +600 MW
    powerConsumed: 0,
    waterConsumed: 50,
    wasteProduced: 0,
    pollutionEmission: 0,
    employeeCapacity: 40,
    constructionTimeTicks: 60,
    spriteKey: 'bld_fusion_plant',
    description: 'Zero-emission tokamak magnetic confinement fusion reactor supplying 600 MW of clean electrical energy.',
    upgradeLevels: [
      { level: 1, name: 'Standard Tokamak Core', cost: 450000, powerOutput: 600 },
      { level: 2, name: 'High-Beta Plasma Stabilizer', cost: 180000, powerOutput: 850 },
      { level: 3, name: 'Superconducting Magnet Upgrade', cost: 320000, powerOutput: 1200 },
      { level: 4, name: 'Helium-3 Aneutronic Fuel Coupling', cost: 550000, powerOutput: 1800 },
      { level: 5, name: 'Quantum Fusion Array', cost: 1000000, powerOutput: 3000 },
    ],
  },
  hydroelectric_dam: {
    id: 'hydroelectric_dam',
    name: 'Grand River Hydroelectric Dam',
    category: 'Infrastructure',
    subcategory: 'Power Generation',
    width: 6,
    height: 3,
    cost: 320000,
    maintenanceCost: 2100,
    powerOutput: 400,
    powerConsumed: 0,
    waterConsumed: 0,
    wasteProduced: 0,
    pollutionEmission: 0,
    employeeCapacity: 25,
    constructionTimeTicks: 90,
    spriteKey: 'bld_hydro_dam',
    description: 'Harnesses river water hydraulic pressure to generate 400 MW of renewable power and control seasonal floods.',
    upgradeLevels: [
      { level: 1, name: 'Kaplan Turbine Generators', cost: 320000, powerOutput: 400 },
      { level: 2, name: 'Variable Speed Pumped Storage', cost: 140000, powerOutput: 600 },
      { level: 3, name: 'AI Water Flow Reservoir Control', cost: 250000, powerOutput: 900 },
    ],
  },
  geothermal_plant: {
    id: 'geothermal_plant',
    name: 'Deep Crust Geothermal Energy Station',
    category: 'Infrastructure',
    subcategory: 'Power Generation',
    width: 3,
    height: 3,
    cost: 220000,
    maintenanceCost: 1600,
    powerOutput: 250,
    powerConsumed: 0,
    waterConsumed: 20,
    wasteProduced: 0,
    pollutionEmission: 0,
    employeeCapacity: 18,
    constructionTimeTicks: 45,
    spriteKey: 'bld_geothermal',
    description: 'Extracts subterranean heat from deep thermal bedrock for continuous zero-emission baseload power.',
  },
  high_speed_rail_terminal: {
    id: 'high_speed_rail_terminal',
    name: 'Bullet Train Central Inter-City Terminal',
    category: 'Transport',
    subcategory: 'Rail Transit',
    width: 5,
    height: 4,
    cost: 500000,
    maintenanceCost: 4200,
    powerConsumed: 80,
    waterConsumed: 30,
    wasteProduced: 25,
    pollutionEmission: 5,
    employeeCapacity: 120,
    passengerCapacity: 25000,
    constructionTimeTicks: 80,
    spriteKey: 'bld_hsr_terminal',
    description: 'High-speed maglev train terminal connecting Metropolis to regional capitals, boosting trade and tourism by 40%.',
  },
  spaceport_orbital: {
    id: 'spaceport_orbital',
    name: 'Commercial Orbital Spaceport',
    category: 'Landmarks',
    subcategory: 'High Tech',
    width: 6,
    height: 6,
    cost: 2500000,
    maintenanceCost: 25000,
    powerConsumed: 350,
    waterConsumed: 120,
    wasteProduced: 80,
    pollutionEmission: 15,
    employeeCapacity: 350,
    landmarkPrestige: 100,
    constructionTimeTicks: 180,
    spriteKey: 'bld_spaceport',
    description: 'The pinnacle of aerospace engineering: launches commercial satellites and orbital space tourism flights.',
  },
};

export function getAdvancedBuildingById(id) {
  return ADVANCED_BUILDINGS_CATALOG[id] || null;
}

export default ADVANCED_BUILDINGS_CATALOG;
