/**
 * CITYMIND Building Definitions & Constants
 * Production-quality comprehensive dataset containing 80+ building types.
 */

export const BUILDING_CATEGORIES = Object.freeze({
  RESIDENTIAL: 'residential',
  COMMERCIAL: 'commercial',
  INDUSTRIAL: 'industrial',
  INFRASTRUCTURE: 'infrastructure',
  TRANSPORT: 'transport',
  PUBLIC_SERVICES: 'public_services',
  ENVIRONMENT: 'environment'
});

export const BUILDING_SUBCATEGORIES = Object.freeze({
  // Residential
  RESIDENTIAL_LOW: 'residential_low',
  RESIDENTIAL_MEDIUM: 'residential_medium',
  RESIDENTIAL_HIGH: 'residential_high',
  RESIDENTIAL_LUXURY: 'residential_luxury',
  // Commercial
  COMMERCIAL_RETAIL: 'commercial_retail',
  COMMERCIAL_OFFICE: 'commercial_office',
  COMMERCIAL_HOTEL: 'commercial_hotel',
  COMMERCIAL_ENTERTAINMENT: 'commercial_entertainment',
  COMMERCIAL_MALL: 'commercial_mall',
  COMMERCIAL_TECH_PARK: 'commercial_tech_park',
  // Industrial
  INDUSTRIAL_LIGHT: 'industrial_light',
  INDUSTRIAL_HEAVY: 'industrial_heavy',
  INDUSTRIAL_HIGH_TECH: 'industrial_high_tech',
  INDUSTRIAL_AGRICULTURE: 'industrial_agriculture',
  INDUSTRIAL_WAREHOUSE: 'industrial_warehouse',
  INDUSTRIAL_RECYCLING: 'industrial_recycling',
  // Infrastructure
  INFRASTRUCTURE_POWER: 'infrastructure_power',
  INFRASTRUCTURE_WATER: 'infrastructure_water',
  INFRASTRUCTURE_SEWAGE: 'infrastructure_sewage',
  INFRASTRUCTURE_TELECOM: 'infrastructure_telecom',
  INFRASTRUCTURE_WASTE: 'infrastructure_waste',
  // Transport
  TRANSPORT_BUS: 'transport_bus',
  TRANSPORT_SUBWAY: 'transport_subway',
  TRANSPORT_TRAIN: 'transport_train',
  TRANSPORT_AIRPORT: 'transport_airport',
  TRANSPORT_SEAPORT: 'transport_seaport',
  TRANSPORT_PARKING: 'transport_parking',
  // Public Services
  PUBLIC_POLICE: 'public_police',
  PUBLIC_FIRE: 'public_fire',
  PUBLIC_HEALTH: 'public_health',
  PUBLIC_EDUCATION: 'public_education',
  PUBLIC_CULTURE: 'public_culture',
  PUBLIC_RECREATION: 'public_recreation',
  // Environment
  ENVIRONMENT_CLEAN_ENERGY: 'environment_clean_energy',
  ENVIRONMENT_CONSERVATION: 'environment_conservation',
  ENVIRONMENT_PURIFICATION: 'environment_purification'
});

/**
 * Helper to generate standardized 5-tier upgrade levels for any building definition.
 */
function generateDefaultUpgrades(baseCost, baseCapacity, basePower, basePollutionAir) {
  return [
    {
      tier: 1,
      name: 'Initial Operation',
      cost: 0,
      statMultipliers: { maintenance: 1.0, capacity: 1.0, power: 1.0, pollution: 1.0, efficiency: 1.0 },
      specialAbilities: ['Standard Operation'],
      resourceRequirements: { steel: 10, concrete: 20, techParts: 5, labor: 10 },
      constructionTimeTicks: 10
    },
    {
      tier: 2,
      name: 'Efficiency Upgrade',
      cost: Math.round(baseCost * 0.4),
      statMultipliers: { maintenance: 1.15, capacity: 1.3, power: 0.9, pollution: 0.85, efficiency: 1.25 },
      specialAbilities: ['Automated Systems'],
      resourceRequirements: { steel: 25, concrete: 40, techParts: 15, labor: 20 },
      constructionTimeTicks: 25
    },
    {
      tier: 3,
      name: 'Expansion Tier I',
      cost: Math.round(baseCost * 0.8),
      statMultipliers: { maintenance: 1.35, capacity: 1.7, power: 1.1, pollution: 0.75, efficiency: 1.5 },
      specialAbilities: ['Capacity Boost', 'Smart Monitoring'],
      resourceRequirements: { steel: 60, concrete: 90, techParts: 45, labor: 40 },
      constructionTimeTicks: 50
    },
    {
      tier: 4,
      name: 'Advanced Automation',
      cost: Math.round(baseCost * 1.5),
      statMultipliers: { maintenance: 1.6, capacity: 2.2, power: 1.25, pollution: 0.6, efficiency: 1.85 },
      specialAbilities: ['AI Optimization', 'Zero-Waste Protocol'],
      resourceRequirements: { steel: 120, concrete: 180, techParts: 100, labor: 75 },
      constructionTimeTicks: 90
    },
    {
      tier: 5,
      name: 'Apex Masterpiece',
      cost: Math.round(baseCost * 3.0),
      statMultipliers: { maintenance: 2.0, capacity: 3.0, power: 1.4, pollution: 0.4, efficiency: 2.5 },
      specialAbilities: ['Maximum Throughput', 'Prestige Landmark Status', 'Autonomous Maintenance'],
      resourceRequirements: { steel: 250, concrete: 400, techParts: 250, labor: 150 },
      constructionTimeTicks: 150
    }
  ];
}

export const BUILDINGS = Object.freeze({
  // ---------------------------------------------------------------------------
  // 1. RESIDENTIAL CATEGORY
  // ---------------------------------------------------------------------------
  // Low Density
  shack: {
    id: 'shack',
    name: 'Makeshift Shack',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_LOW,
    size: [1, 1],
    cost: 1500,
    maintenanceCost: 10,
    powerConsumption: 1,
    waterConsumption: 1,
    wasteProduction: 2,
    pollutionEmission: { air: 2, noise: 1, water: 2 },
    employeeCapacity: 0,
    residentialCapacity: 2,
    taxRevenueBase: 15,
    happinessBonus: -5,
    serviceRadius: 0,
    healthImpact: -2,
    educationImpact: 0,
    crimeReduction: 0,
    landmarkPrestige: 0,
    upgradeLevels: generateDefaultUpgrades(1500, 2, 1, 2),
    constructionTimeTicks: 2,
    spriteKey: 'res_shack_01',
    soundEffects: { build: 'sfx_build_wood', ambient: 'sfx_amb_slum', action: 'sfx_door_creak' }
  },
  tiny_cottage: {
    id: 'tiny_cottage',
    name: 'Tiny Cottage',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_LOW,
    size: [1, 1],
    cost: 12000,
    maintenanceCost: 40,
    powerConsumption: 2,
    waterConsumption: 2,
    wasteProduction: 3,
    pollutionEmission: { air: 0, noise: 1, water: 0 },
    employeeCapacity: 0,
    residentialCapacity: 4,
    taxRevenueBase: 120,
    happinessBonus: 3,
    serviceRadius: 0,
    healthImpact: 1,
    educationImpact: 0,
    crimeReduction: 0,
    landmarkPrestige: 1,
    upgradeLevels: generateDefaultUpgrades(12000, 4, 2, 0),
    constructionTimeTicks: 5,
    spriteKey: 'res_cottage_01',
    soundEffects: { build: 'sfx_build_wood', ambient: 'sfx_amb_suburb', action: 'sfx_door_close' }
  },
  suburban_house: {
    id: 'suburban_house',
    name: 'Suburban Family House',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_LOW,
    size: [2, 2],
    cost: 35000,
    maintenanceCost: 90,
    powerConsumption: 5,
    waterConsumption: 4,
    wasteProduction: 6,
    pollutionEmission: { air: 0, noise: 2, water: 0 },
    employeeCapacity: 0,
    residentialCapacity: 6,
    taxRevenueBase: 350,
    happinessBonus: 8,
    serviceRadius: 0,
    healthImpact: 2,
    educationImpact: 1,
    crimeReduction: 0,
    landmarkPrestige: 2,
    upgradeLevels: generateDefaultUpgrades(35000, 6, 5, 0),
    constructionTimeTicks: 10,
    spriteKey: 'res_suburban_01',
    soundEffects: { build: 'sfx_build_house', ambient: 'sfx_amb_suburb', action: 'sfx_lawnmower' }
  },
  townhouse: {
    id: 'townhouse',
    name: 'Row Townhouse',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_LOW,
    size: [1, 2],
    cost: 55000,
    maintenanceCost: 140,
    powerConsumption: 7,
    waterConsumption: 5,
    wasteProduction: 8,
    pollutionEmission: { air: 0, noise: 2, water: 0 },
    employeeCapacity: 0,
    residentialCapacity: 12,
    taxRevenueBase: 600,
    happinessBonus: 6,
    serviceRadius: 0,
    healthImpact: 2,
    educationImpact: 1,
    crimeReduction: 0,
    landmarkPrestige: 3,
    upgradeLevels: generateDefaultUpgrades(55000, 12, 7, 0),
    constructionTimeTicks: 14,
    spriteKey: 'res_townhouse_01',
    soundEffects: { build: 'sfx_build_brick', ambient: 'sfx_amb_city_quiet', action: 'sfx_door_bell' }
  },
  suburban_villa: {
    id: 'suburban_villa',
    name: 'Modern Suburban Villa',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_LOW,
    size: [2, 2],
    cost: 95000,
    maintenanceCost: 220,
    powerConsumption: 12,
    waterConsumption: 9,
    wasteProduction: 10,
    pollutionEmission: { air: 0, noise: 1, water: 0 },
    employeeCapacity: 0,
    residentialCapacity: 8,
    taxRevenueBase: 1100,
    happinessBonus: 14,
    serviceRadius: 0,
    healthImpact: 4,
    educationImpact: 2,
    crimeReduction: 1,
    landmarkPrestige: 5,
    upgradeLevels: generateDefaultUpgrades(95000, 8, 12, 0),
    constructionTimeTicks: 18,
    spriteKey: 'res_villa_01',
    soundEffects: { build: 'sfx_build_house', ambient: 'sfx_amb_suburb_rich', action: 'sfx_gate_open' }
  },

  // Medium Density
  low_rise_apartment: {
    id: 'low_rise_apartment',
    name: 'Low-Rise Apartment Block',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_MEDIUM,
    size: [2, 2],
    cost: 110000,
    maintenanceCost: 320,
    powerConsumption: 18,
    waterConsumption: 14,
    wasteProduction: 22,
    pollutionEmission: { air: 1, noise: 4, water: 1 },
    employeeCapacity: 2,
    residentialCapacity: 32,
    taxRevenueBase: 1450,
    happinessBonus: 5,
    serviceRadius: 0,
    healthImpact: 1,
    educationImpact: 1,
    crimeReduction: 0,
    landmarkPrestige: 2,
    upgradeLevels: generateDefaultUpgrades(110000, 32, 18, 1),
    constructionTimeTicks: 22,
    spriteKey: 'res_lowrise_01',
    soundEffects: { build: 'sfx_build_concrete', ambient: 'sfx_amb_apt', action: 'sfx_elevator_chime' }
  },
  courtyard_flat: {
    id: 'courtyard_flat',
    name: 'Courtyard Apartments',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_MEDIUM,
    size: [3, 2],
    cost: 175000,
    maintenanceCost: 480,
    powerConsumption: 26,
    waterConsumption: 20,
    wasteProduction: 30,
    pollutionEmission: { air: 0, noise: 3, water: 0 },
    employeeCapacity: 3,
    residentialCapacity: 50,
    taxRevenueBase: 2200,
    happinessBonus: 9,
    serviceRadius: 0,
    healthImpact: 3,
    educationImpact: 2,
    crimeReduction: 1,
    landmarkPrestige: 4,
    upgradeLevels: generateDefaultUpgrades(175000, 50, 26, 0),
    constructionTimeTicks: 28,
    spriteKey: 'res_courtyard_01',
    soundEffects: { build: 'sfx_build_concrete', ambient: 'sfx_amb_courtyard', action: 'sfx_children_playing' }
  },
  condo_complex: {
    id: 'condo_complex',
    name: 'Mid-Rise Condo Complex',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_MEDIUM,
    size: [3, 3],
    cost: 290000,
    maintenanceCost: 750,
    powerConsumption: 42,
    waterConsumption: 32,
    wasteProduction: 48,
    pollutionEmission: { air: 1, noise: 5, water: 1 },
    employeeCapacity: 5,
    residentialCapacity: 95,
    taxRevenueBase: 4100,
    happinessBonus: 10,
    serviceRadius: 0,
    healthImpact: 3,
    educationImpact: 2,
    crimeReduction: 2,
    landmarkPrestige: 5,
    upgradeLevels: generateDefaultUpgrades(290000, 95, 42, 1),
    constructionTimeTicks: 36,
    spriteKey: 'res_condo_01',
    soundEffects: { build: 'sfx_build_crane', ambient: 'sfx_amb_city_mid', action: 'sfx_hvac_hum' }
  },
  micro_apartments: {
    id: 'micro_apartments',
    name: 'Micro-Apartment Hub',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_MEDIUM,
    size: [2, 2],
    cost: 210000,
    maintenanceCost: 550,
    powerConsumption: 35,
    waterConsumption: 28,
    wasteProduction: 45,
    pollutionEmission: { air: 1, noise: 6, water: 2 },
    employeeCapacity: 4,
    residentialCapacity: 120,
    taxRevenueBase: 3200,
    happinessBonus: 1,
    serviceRadius: 0,
    healthImpact: -1,
    educationImpact: 1,
    crimeReduction: -1,
    landmarkPrestige: 2,
    upgradeLevels: generateDefaultUpgrades(210000, 120, 35, 1),
    constructionTimeTicks: 25,
    spriteKey: 'res_micro_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_crowd_dense', action: 'sfx_vending_machine' }
  },

  // High Density
  high_rise_apartment: {
    id: 'high_rise_apartment',
    name: 'High-Rise Apartment Tower',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_HIGH,
    size: [3, 3],
    cost: 650000,
    maintenanceCost: 1800,
    powerConsumption: 85,
    waterConsumption: 65,
    wasteProduction: 95,
    pollutionEmission: { air: 2, noise: 8, water: 3 },
    employeeCapacity: 10,
    residentialCapacity: 280,
    taxRevenueBase: 9500,
    happinessBonus: 8,
    serviceRadius: 0,
    healthImpact: 2,
    educationImpact: 2,
    crimeReduction: 0,
    landmarkPrestige: 6,
    upgradeLevels: generateDefaultUpgrades(650000, 280, 85, 2),
    constructionTimeTicks: 45,
    spriteKey: 'res_highrise_01',
    soundEffects: { build: 'sfx_build_crane', ambient: 'sfx_amb_tower_hum', action: 'sfx_express_elevator' }
  },
  residential_skyscraper: {
    id: 'residential_skyscraper',
    name: 'Skyline Residential Tower',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_HIGH,
    size: [4, 4],
    cost: 1450000,
    maintenanceCost: 4200,
    powerConsumption: 190,
    waterConsumption: 145,
    wasteProduction: 210,
    pollutionEmission: { air: 3, noise: 10, water: 4 },
    employeeCapacity: 25,
    residentialCapacity: 650,
    taxRevenueBase: 22000,
    happinessBonus: 12,
    serviceRadius: 0,
    healthImpact: 4,
    educationImpact: 3,
    crimeReduction: 1,
    landmarkPrestige: 10,
    upgradeLevels: generateDefaultUpgrades(1450000, 650, 190, 3),
    constructionTimeTicks: 65,
    spriteKey: 'res_skyscraper_01',
    soundEffects: { build: 'sfx_build_mega', ambient: 'sfx_amb_skyscraper', action: 'sfx_wind_high' }
  },
  megablock_housing: {
    id: 'megablock_housing',
    name: 'Autonomous Megablock Housing',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_HIGH,
    size: [5, 5],
    cost: 3200000,
    maintenanceCost: 9500,
    powerConsumption: 420,
    waterConsumption: 330,
    wasteProduction: 480,
    pollutionEmission: { air: 5, noise: 14, water: 6 },
    employeeCapacity: 60,
    residentialCapacity: 1600,
    taxRevenueBase: 51000,
    happinessBonus: 6,
    serviceRadius: 2,
    healthImpact: 3,
    educationImpact: 4,
    crimeReduction: 2,
    landmarkPrestige: 14,
    upgradeLevels: generateDefaultUpgrades(3200000, 1600, 420, 5),
    constructionTimeTicks: 100,
    spriteKey: 'res_megablock_01',
    soundEffects: { build: 'sfx_build_heavy', ambient: 'sfx_amb_megablock', action: 'sfx_drone_delivery' }
  },
  co_living_tower: {
    id: 'co_living_tower',
    name: 'NextGen Co-Living Spire',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_HIGH,
    size: [3, 3],
    cost: 890000,
    maintenanceCost: 2600,
    powerConsumption: 110,
    waterConsumption: 85,
    wasteProduction: 115,
    pollutionEmission: { air: 1, noise: 6, water: 2 },
    employeeCapacity: 18,
    residentialCapacity: 380,
    taxRevenueBase: 13500,
    happinessBonus: 15,
    serviceRadius: 1,
    healthImpact: 5,
    educationImpact: 4,
    crimeReduction: 3,
    landmarkPrestige: 8,
    upgradeLevels: generateDefaultUpgrades(890000, 380, 110, 1),
    constructionTimeTicks: 52,
    spriteKey: 'res_coliving_01',
    soundEffects: { build: 'sfx_build_glass', ambient: 'sfx_amb_lounge', action: 'sfx_coffee_espresso' }
  },

  // Luxury
  penthouse_tower: {
    id: 'penthouse_tower',
    name: 'Grand Penthouse Spire',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_LUXURY,
    size: [3, 3],
    cost: 2100000,
    maintenanceCost: 6500,
    powerConsumption: 240,
    waterConsumption: 180,
    wasteProduction: 140,
    pollutionEmission: { air: 1, noise: 3, water: 1 },
    employeeCapacity: 30,
    residentialCapacity: 120,
    taxRevenueBase: 48000,
    happinessBonus: 25,
    serviceRadius: 0,
    healthImpact: 8,
    educationImpact: 5,
    crimeReduction: 5,
    landmarkPrestige: 20,
    upgradeLevels: generateDefaultUpgrades(2100000, 120, 240, 1),
    constructionTimeTicks: 70,
    spriteKey: 'res_penthouse_01',
    soundEffects: { build: 'sfx_build_luxury', ambient: 'sfx_amb_luxury', action: 'sfx_champagne_pop' }
  },
  gated_estate: {
    id: 'gated_estate',
    name: 'Private Gated Estate',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_LUXURY,
    size: [4, 4],
    cost: 1800000,
    maintenanceCost: 4800,
    powerConsumption: 160,
    waterConsumption: 150,
    wasteProduction: 90,
    pollutionEmission: { air: 0, noise: 1, water: 0 },
    employeeCapacity: 15,
    residentialCapacity: 24,
    taxRevenueBase: 39000,
    happinessBonus: 22,
    serviceRadius: 0,
    healthImpact: 10,
    educationImpact: 6,
    crimeReduction: 8,
    landmarkPrestige: 18,
    upgradeLevels: generateDefaultUpgrades(1800000, 24, 160, 0),
    constructionTimeTicks: 60,
    spriteKey: 'res_estate_01',
    soundEffects: { build: 'sfx_build_stone', ambient: 'sfx_amb_fountain', action: 'sfx_security_gate' }
  },
  waterfront_villa: {
    id: 'waterfront_villa',
    name: 'Oceanfront Luxury Haven',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_LUXURY,
    size: [3, 3],
    cost: 2600000,
    maintenanceCost: 7200,
    powerConsumption: 210,
    waterConsumption: 190,
    wasteProduction: 110,
    pollutionEmission: { air: 0, noise: 1, water: 1 },
    employeeCapacity: 20,
    residentialCapacity: 16,
    taxRevenueBase: 58000,
    happinessBonus: 30,
    serviceRadius: 0,
    healthImpact: 12,
    educationImpact: 5,
    crimeReduction: 6,
    landmarkPrestige: 25,
    upgradeLevels: generateDefaultUpgrades(2600000, 16, 210, 0),
    constructionTimeTicks: 75,
    spriteKey: 'res_waterfront_01',
    soundEffects: { build: 'sfx_build_luxury', ambient: 'sfx_amb_waves', action: 'sfx_yacht_horn' }
  },
  eco_luxury_mansion: {
    id: 'eco_luxury_mansion',
    name: 'Zero-Carbon Eco Mansion',
    category: BUILDING_CATEGORIES.RESIDENTIAL,
    subcategory: BUILDING_SUBCATEGORIES.RESIDENTIAL_LUXURY,
    size: [4, 4],
    cost: 3800000,
    maintenanceCost: 3500,
    powerConsumption: -10, // Self-sustaining
    waterConsumption: -5,  // Rain harvesting
    wasteProduction: 15,
    pollutionEmission: { air: -5, noise: 0, water: -2 },
    employeeCapacity: 25,
    residentialCapacity: 20,
    taxRevenueBase: 72000,
    happinessBonus: 35,
    serviceRadius: 2,
    healthImpact: 15,
    educationImpact: 8,
    crimeReduction: 7,
    landmarkPrestige: 30,
    upgradeLevels: generateDefaultUpgrades(3800000, 20, -10, -5),
    constructionTimeTicks: 90,
    spriteKey: 'res_ecomansion_01',
    soundEffects: { build: 'sfx_build_green', ambient: 'sfx_amb_nature_soft', action: 'sfx_solar_panel_active' }
  },

  // ---------------------------------------------------------------------------
  // 2. COMMERCIAL CATEGORY
  // ---------------------------------------------------------------------------
  corner_store: {
    id: 'corner_store',
    name: 'Neighborhood Corner Shop',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_RETAIL,
    size: [1, 1],
    cost: 18000,
    maintenanceCost: 80,
    powerConsumption: 4,
    waterConsumption: 2,
    wasteProduction: 5,
    pollutionEmission: { air: 0, noise: 2, water: 0 },
    employeeCapacity: 4,
    residentialCapacity: 0,
    taxRevenueBase: 450,
    happinessBonus: 4,
    serviceRadius: 4,
    healthImpact: 0,
    educationImpact: 0,
    crimeReduction: 0,
    landmarkPrestige: 1,
    upgradeLevels: generateDefaultUpgrades(18000, 4, 4, 0),
    constructionTimeTicks: 6,
    spriteKey: 'com_corner_01',
    soundEffects: { build: 'sfx_build_shop', ambient: 'sfx_amb_register', action: 'sfx_cash_register' }
  },
  supermarket: {
    id: 'supermarket',
    name: 'City Market Superstore',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_RETAIL,
    size: [3, 2],
    cost: 140000,
    maintenanceCost: 520,
    powerConsumption: 32,
    waterConsumption: 16,
    wasteProduction: 45,
    pollutionEmission: { air: 1, noise: 5, water: 1 },
    employeeCapacity: 35,
    residentialCapacity: 0,
    taxRevenueBase: 3800,
    happinessBonus: 8,
    serviceRadius: 8,
    healthImpact: 2,
    educationImpact: 0,
    crimeReduction: 0,
    landmarkPrestige: 3,
    upgradeLevels: generateDefaultUpgrades(140000, 35, 32, 1),
    constructionTimeTicks: 20,
    spriteKey: 'com_supermarket_01',
    soundEffects: { build: 'sfx_build_retail', ambient: 'sfx_amb_store_chatter', action: 'sfx_scanner_beep' }
  },
  boutique_street: {
    id: 'boutique_street',
    name: 'Artisan Boutique Arcade',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_RETAIL,
    size: [2, 2],
    cost: 95000,
    maintenanceCost: 380,
    powerConsumption: 18,
    waterConsumption: 10,
    wasteProduction: 20,
    pollutionEmission: { air: 0, noise: 3, water: 0 },
    employeeCapacity: 20,
    residentialCapacity: 0,
    taxRevenueBase: 2800,
    happinessBonus: 10,
    serviceRadius: 6,
    healthImpact: 1,
    educationImpact: 1,
    crimeReduction: 1,
    landmarkPrestige: 5,
    upgradeLevels: generateDefaultUpgrades(95000, 20, 18, 0),
    constructionTimeTicks: 16,
    spriteKey: 'com_boutique_01',
    soundEffects: { build: 'sfx_build_brick', ambient: 'sfx_amb_cafe_chatter', action: 'sfx_espresso_machine' }
  },
  shopping_plaza: {
    id: 'shopping_plaza',
    name: 'Open-Air Shopping Plaza',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_RETAIL,
    size: [4, 3],
    cost: 420000,
    maintenanceCost: 1400,
    powerConsumption: 85,
    waterConsumption: 40,
    wasteProduction: 110,
    pollutionEmission: { air: 2, noise: 8, water: 2 },
    employeeCapacity: 110,
    residentialCapacity: 0,
    taxRevenueBase: 12500,
    happinessBonus: 14,
    serviceRadius: 12,
    healthImpact: 3,
    educationImpact: 1,
    crimeReduction: 1,
    landmarkPrestige: 7,
    upgradeLevels: generateDefaultUpgrades(420000, 110, 85, 2),
    constructionTimeTicks: 38,
    spriteKey: 'com_plaza_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_plaza', action: 'sfx_fountain_splash' }
  },
  small_office: {
    id: 'small_office',
    name: 'Local Business Office',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_OFFICE,
    size: [2, 2],
    cost: 85000,
    maintenanceCost: 310,
    powerConsumption: 20,
    waterConsumption: 12,
    wasteProduction: 18,
    pollutionEmission: { air: 1, noise: 3, water: 0 },
    employeeCapacity: 30,
    residentialCapacity: 0,
    taxRevenueBase: 2400,
    happinessBonus: 3,
    serviceRadius: 5,
    healthImpact: 0,
    educationImpact: 2,
    crimeReduction: 0,
    landmarkPrestige: 2,
    upgradeLevels: generateDefaultUpgrades(85000, 30, 20, 1),
    constructionTimeTicks: 15,
    spriteKey: 'com_office_small_01',
    soundEffects: { build: 'sfx_build_brick', ambient: 'sfx_amb_office_typing', action: 'sfx_printer_running' }
  },
  corporate_branch: {
    id: 'corporate_branch',
    name: 'Corporate Regional Branch',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_OFFICE,
    size: [3, 3],
    cost: 380000,
    maintenanceCost: 1250,
    powerConsumption: 75,
    waterConsumption: 35,
    wasteProduction: 65,
    pollutionEmission: { air: 1, noise: 4, water: 1 },
    employeeCapacity: 140,
    residentialCapacity: 0,
    taxRevenueBase: 11500,
    happinessBonus: 6,
    serviceRadius: 8,
    healthImpact: 1,
    educationImpact: 3,
    crimeReduction: 1,
    landmarkPrestige: 6,
    upgradeLevels: generateDefaultUpgrades(380000, 140, 75, 1),
    constructionTimeTicks: 32,
    spriteKey: 'com_corp_branch_01',
    soundEffects: { build: 'sfx_build_glass', ambient: 'sfx_amb_office_hum', action: 'sfx_phone_ring' }
  },
  financial_center: {
    id: 'financial_center',
    name: 'Financial Exchange Tower',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_OFFICE,
    size: [4, 4],
    cost: 2200000,
    maintenanceCost: 6800,
    powerConsumption: 310,
    waterConsumption: 120,
    wasteProduction: 180,
    pollutionEmission: { air: 2, noise: 6, water: 2 },
    employeeCapacity: 750,
    residentialCapacity: 0,
    taxRevenueBase: 68000,
    happinessBonus: 10,
    serviceRadius: 15,
    healthImpact: 2,
    educationImpact: 5,
    crimeReduction: 3,
    landmarkPrestige: 16,
    upgradeLevels: generateDefaultUpgrades(2200000, 750, 310, 2),
    constructionTimeTicks: 80,
    spriteKey: 'com_financial_01',
    soundEffects: { build: 'sfx_build_crane', ambient: 'sfx_amb_stock_floor', action: 'sfx_bell_ring' }
  },
  skyscraper_office: {
    id: 'skyscraper_office',
    name: 'International Trade Spire',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_OFFICE,
    size: [4, 4],
    cost: 4500000,
    maintenanceCost: 13500,
    powerConsumption: 580,
    waterConsumption: 240,
    wasteProduction: 320,
    pollutionEmission: { air: 3, noise: 8, water: 3 },
    employeeCapacity: 1600,
    residentialCapacity: 0,
    taxRevenueBase: 140000,
    happinessBonus: 15,
    serviceRadius: 20,
    healthImpact: 3,
    educationImpact: 8,
    crimeReduction: 4,
    landmarkPrestige: 25,
    upgradeLevels: generateDefaultUpgrades(4500000, 1600, 580, 3),
    constructionTimeTicks: 120,
    spriteKey: 'com_skyscraper_office_01',
    soundEffects: { build: 'sfx_build_mega', ambient: 'sfx_amb_highrise', action: 'sfx_server_fans' }
  },
  budget_motel: {
    id: 'budget_motel',
    name: 'Highway Express Motel',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_HOTEL,
    size: [2, 2],
    cost: 65000,
    maintenanceCost: 260,
    powerConsumption: 16,
    waterConsumption: 18,
    wasteProduction: 25,
    pollutionEmission: { air: 1, noise: 4, water: 1 },
    employeeCapacity: 12,
    residentialCapacity: 0,
    taxRevenueBase: 1600,
    happinessBonus: 2,
    serviceRadius: 6,
    healthImpact: -1,
    educationImpact: 0,
    crimeReduction: -1,
    landmarkPrestige: 1,
    upgradeLevels: generateDefaultUpgrades(65000, 12, 16, 1),
    constructionTimeTicks: 14,
    spriteKey: 'com_motel_01',
    soundEffects: { build: 'sfx_build_brick', ambient: 'sfx_amb_neon_hum', action: 'sfx_ice_machine' }
  },
  boutique_hotel: {
    id: 'boutique_hotel',
    name: 'Heritage Boutique Hotel',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_HOTEL,
    size: [3, 2],
    cost: 320000,
    maintenanceCost: 1100,
    powerConsumption: 48,
    waterConsumption: 42,
    wasteProduction: 50,
    pollutionEmission: { air: 0, noise: 2, water: 1 },
    employeeCapacity: 45,
    residentialCapacity: 0,
    taxRevenueBase: 9200,
    happinessBonus: 12,
    serviceRadius: 10,
    healthImpact: 3,
    educationImpact: 2,
    crimeReduction: 2,
    landmarkPrestige: 9,
    upgradeLevels: generateDefaultUpgrades(320000, 45, 48, 0),
    constructionTimeTicks: 30,
    spriteKey: 'com_hotel_boutique_01',
    soundEffects: { build: 'sfx_build_glass', ambient: 'sfx_amb_hotel_lobby', action: 'sfx_valet_horn' }
  },
  luxury_resort: {
    id: 'luxury_resort',
    name: 'Grand Bay Eco Resort',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_HOTEL,
    size: [5, 4],
    cost: 2800000,
    maintenanceCost: 8900,
    powerConsumption: 290,
    waterConsumption: 320,
    wasteProduction: 280,
    pollutionEmission: { air: 1, noise: 3, water: 2 },
    employeeCapacity: 320,
    residentialCapacity: 0,
    taxRevenueBase: 82000,
    happinessBonus: 28,
    serviceRadius: 18,
    healthImpact: 8,
    educationImpact: 4,
    crimeReduction: 4,
    landmarkPrestige: 22,
    upgradeLevels: generateDefaultUpgrades(2800000, 320, 290, 1),
    constructionTimeTicks: 95,
    spriteKey: 'com_resort_01',
    soundEffects: { build: 'sfx_build_luxury', ambient: 'sfx_amb_pool_side', action: 'sfx_cocktail_shaker' }
  },
  cinema_complex: {
    id: 'cinema_complex',
    name: 'Multiplex Cinema & IMAX',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_ENTERTAINMENT,
    size: [3, 3],
    cost: 340000,
    maintenanceCost: 1150,
    powerConsumption: 65,
    waterConsumption: 25,
    wasteProduction: 70,
    pollutionEmission: { air: 1, noise: 8, water: 1 },
    employeeCapacity: 40,
    residentialCapacity: 0,
    taxRevenueBase: 8800,
    happinessBonus: 18,
    serviceRadius: 12,
    healthImpact: 2,
    educationImpact: 3,
    crimeReduction: 1,
    landmarkPrestige: 6,
    upgradeLevels: generateDefaultUpgrades(340000, 40, 65, 1),
    constructionTimeTicks: 34,
    spriteKey: 'com_cinema_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_popcorn', action: 'sfx_movie_fanfare' }
  },
  nightclub: {
    id: 'nightclub',
    name: 'Pulse Neon Nightclub',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_ENTERTAINMENT,
    size: [2, 2],
    cost: 160000,
    maintenanceCost: 650,
    powerConsumption: 35,
    waterConsumption: 20,
    wasteProduction: 40,
    pollutionEmission: { air: 1, noise: 15, water: 2 },
    employeeCapacity: 25,
    residentialCapacity: 0,
    taxRevenueBase: 5200,
    happinessBonus: 12,
    serviceRadius: 8,
    healthImpact: -2,
    educationImpact: 0,
    crimeReduction: -3,
    landmarkPrestige: 4,
    upgradeLevels: generateDefaultUpgrades(160000, 25, 35, 1),
    constructionTimeTicks: 20,
    spriteKey: 'com_nightclub_01',
    soundEffects: { build: 'sfx_build_brick', ambient: 'sfx_amb_edm_bass', action: 'sfx_cheering_crowd' }
  },
  theme_park: {
    id: 'theme_park',
    name: 'Wonderland Theme Park',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_ENTERTAINMENT,
    size: [6, 6],
    cost: 5500000,
    maintenanceCost: 18000,
    powerConsumption: 650,
    waterConsumption: 480,
    wasteProduction: 750,
    pollutionEmission: { air: 4, noise: 20, water: 5 },
    employeeCapacity: 850,
    residentialCapacity: 0,
    taxRevenueBase: 165000,
    happinessBonus: 40,
    serviceRadius: 30,
    healthImpact: 6,
    educationImpact: 5,
    crimeReduction: 2,
    landmarkPrestige: 35,
    upgradeLevels: generateDefaultUpgrades(5500000, 850, 650, 4),
    constructionTimeTicks: 140,
    spriteKey: 'com_themepark_01',
    soundEffects: { build: 'sfx_build_mega', ambient: 'sfx_amb_rollercoaster', action: 'sfx_screams_joy' }
  },
  mega_mall: {
    id: 'mega_mall',
    name: 'Metropolitan Mega Mall',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_MALL,
    size: [5, 5],
    cost: 3400000,
    maintenanceCost: 11000,
    powerConsumption: 450,
    waterConsumption: 280,
    wasteProduction: 550,
    pollutionEmission: { air: 4, noise: 12, water: 4 },
    employeeCapacity: 650,
    residentialCapacity: 0,
    taxRevenueBase: 105000,
    happinessBonus: 24,
    serviceRadius: 20,
    healthImpact: 3,
    educationImpact: 2,
    crimeReduction: 2,
    landmarkPrestige: 18,
    upgradeLevels: generateDefaultUpgrades(3400000, 650, 450, 4),
    constructionTimeTicks: 105,
    spriteKey: 'com_megamall_01',
    soundEffects: { build: 'sfx_build_heavy', ambient: 'sfx_amb_mall_echo', action: 'sfx_escalator' }
  },
  tech_campus: {
    id: 'tech_campus',
    name: 'Silicon Hub Tech Campus',
    category: BUILDING_CATEGORIES.COMMERCIAL,
    subcategory: BUILDING_SUBCATEGORIES.COMMERCIAL_TECH_PARK,
    size: [4, 4],
    cost: 3900000,
    maintenanceCost: 12000,
    powerConsumption: 520,
    waterConsumption: 180,
    wasteProduction: 210,
    pollutionEmission: { air: 1, noise: 3, water: 1 },
    employeeCapacity: 1100,
    residentialCapacity: 0,
    taxRevenueBase: 130000,
    happinessBonus: 20,
    serviceRadius: 22,
    healthImpact: 6,
    educationImpact: 15,
    crimeReduction: 5,
    landmarkPrestige: 24,
    upgradeLevels: generateDefaultUpgrades(3900000, 1100, 520, 1),
    constructionTimeTicks: 110,
    spriteKey: 'com_techpark_01',
    soundEffects: { build: 'sfx_build_futuristic', ambient: 'sfx_amb_cleanroom', action: 'sfx_keyboard_typing' }
  },

  // ---------------------------------------------------------------------------
  // 3. INDUSTRIAL CATEGORY
  // ---------------------------------------------------------------------------
  workshop: {
    id: 'workshop',
    name: 'Craftsman Workshop',
    category: BUILDING_CATEGORIES.INDUSTRIAL,
    subcategory: BUILDING_SUBCATEGORIES.INDUSTRIAL_LIGHT,
    size: [1, 2],
    cost: 28000,
    maintenanceCost: 120,
    powerConsumption: 8,
    waterConsumption: 4,
    wasteProduction: 12,
    pollutionEmission: { air: 3, noise: 5, water: 2 },
    employeeCapacity: 10,
    residentialCapacity: 0,
    taxRevenueBase: 750,
    happinessBonus: 0,
    serviceRadius: 0,
    healthImpact: -1,
    educationImpact: 1,
    crimeReduction: 0,
    landmarkPrestige: 1,
    upgradeLevels: generateDefaultUpgrades(28000, 10, 8, 3),
    constructionTimeTicks: 8,
    spriteKey: 'ind_workshop_01',
    soundEffects: { build: 'sfx_build_wood', ambient: 'sfx_amb_sawing', action: 'sfx_hammer_strike' }
  },
  electronics_assembly: {
    id: 'electronics_assembly',
    name: 'Precision Electronics Assembly',
    category: BUILDING_CATEGORIES.INDUSTRIAL,
    subcategory: BUILDING_SUBCATEGORIES.INDUSTRIAL_LIGHT,
    size: [3, 2],
    cost: 210000,
    maintenanceCost: 780,
    powerConsumption: 45,
    waterConsumption: 25,
    wasteProduction: 35,
    pollutionEmission: { air: 2, noise: 4, water: 3 },
    employeeCapacity: 85,
    residentialCapacity: 0,
    taxRevenueBase: 6500,
    happinessBonus: 2,
    serviceRadius: 0,
    healthImpact: -1,
    educationImpact: 4,
    crimeReduction: 1,
    landmarkPrestige: 4,
    upgradeLevels: generateDefaultUpgrades(210000, 85, 45, 2),
    constructionTimeTicks: 24,
    spriteKey: 'ind_electronics_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_conveyor', action: 'sfx_soldering' }
  },
  steel_mill: {
    id: 'steel_mill',
    name: 'Heavy Alloy Steel Mill',
    category: BUILDING_CATEGORIES.INDUSTRIAL,
    subcategory: BUILDING_SUBCATEGORIES.INDUSTRIAL_HEAVY,
    size: [4, 4],
    cost: 1200000,
    maintenanceCost: 4500,
    powerConsumption: 320,
    waterConsumption: 210,
    wasteProduction: 420,
    pollutionEmission: { air: 35, noise: 25, water: 20 },
    employeeCapacity: 350,
    residentialCapacity: 0,
    taxRevenueBase: 38000,
    happinessBonus: -15,
    serviceRadius: 0,
    healthImpact: -12,
    educationImpact: 0,
    crimeReduction: -2,
    landmarkPrestige: 3,
    upgradeLevels: generateDefaultUpgrades(1200000, 350, 320, 35),
    constructionTimeTicks: 70,
    spriteKey: 'ind_steelmill_01',
    soundEffects: { build: 'sfx_build_heavy', ambient: 'sfx_amb_blast_furnace', action: 'sfx_metal_clash' }
  },
  chemical_works: {
    id: 'chemical_works',
    name: 'Industrial Chemical Complex',
    category: BUILDING_CATEGORIES.INDUSTRIAL,
    subcategory: BUILDING_SUBCATEGORIES.INDUSTRIAL_HEAVY,
    size: [4, 3],
    cost: 1450000,
    maintenanceCost: 5200,
    powerConsumption: 280,
    waterConsumption: 310,
    wasteProduction: 550,
    pollutionEmission: { air: 45, noise: 18, water: 40 },
    employeeCapacity: 280,
    residentialCapacity: 0,
    taxRevenueBase: 44000,
    happinessBonus: -20,
    serviceRadius: 0,
    healthImpact: -18,
    educationImpact: 2,
    crimeReduction: -2,
    landmarkPrestige: 2,
    upgradeLevels: generateDefaultUpgrades(1450000, 280, 280, 45),
    constructionTimeTicks: 75,
    spriteKey: 'ind_chemical_01',
    soundEffects: { build: 'sfx_build_heavy', ambient: 'sfx_amb_steam_hiss', action: 'sfx_liquid_flow' }
  },
  auto_plant: {
    id: 'auto_plant',
    name: 'Automated Vehicle Plant',
    category: BUILDING_CATEGORIES.INDUSTRIAL,
    subcategory: BUILDING_SUBCATEGORIES.INDUSTRIAL_HEAVY,
    size: [5, 4],
    cost: 2100000,
    maintenanceCost: 6800,
    powerConsumption: 410,
    waterConsumption: 190,
    wasteProduction: 380,
    pollutionEmission: { air: 22, noise: 20, water: 15 },
    employeeCapacity: 550,
    residentialCapacity: 0,
    taxRevenueBase: 65000,
    happinessBonus: -5,
    serviceRadius: 0,
    healthImpact: -8,
    educationImpact: 3,
    crimeReduction: 0,
    landmarkPrestige: 6,
    upgradeLevels: generateDefaultUpgrades(2100000, 550, 410, 22),
    constructionTimeTicks: 85,
    spriteKey: 'ind_autoplant_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_robot_arms', action: 'sfx_weld_spark' }
  },
  semiconductor_fab: {
    id: 'semiconductor_fab',
    name: 'Nanometer Semiconductor Fab',
    category: BUILDING_CATEGORIES.INDUSTRIAL,
    subcategory: BUILDING_SUBCATEGORIES.INDUSTRIAL_HIGH_TECH,
    size: [4, 4],
    cost: 4800000,
    maintenanceCost: 15000,
    powerConsumption: 680,
    waterConsumption: 450,
    wasteProduction: 180,
    pollutionEmission: { air: 3, noise: 2, water: 8 },
    employeeCapacity: 600,
    residentialCapacity: 0,
    taxRevenueBase: 160000,
    happinessBonus: 10,
    serviceRadius: 0,
    healthImpact: 2,
    educationImpact: 18,
    crimeReduction: 4,
    landmarkPrestige: 20,
    upgradeLevels: generateDefaultUpgrades(4800000, 600, 680, 3),
    constructionTimeTicks: 130,
    spriteKey: 'ind_semicon_01',
    soundEffects: { build: 'sfx_build_futuristic', ambient: 'sfx_amb_cleanroom_air', action: 'sfx_laser_etch' }
  },
  biotech_lab: {
    id: 'biotech_lab',
    name: 'Genomic Biotech Institute',
    category: BUILDING_CATEGORIES.INDUSTRIAL,
    subcategory: BUILDING_SUBCATEGORIES.INDUSTRIAL_HIGH_TECH,
    size: [3, 3],
    cost: 2900000,
    maintenanceCost: 9200,
    powerConsumption: 340,
    waterConsumption: 220,
    wasteProduction: 120,
    pollutionEmission: { air: 1, noise: 1, water: 5 },
    employeeCapacity: 320,
    residentialCapacity: 0,
    taxRevenueBase: 95000,
    happinessBonus: 15,
    serviceRadius: 5,
    healthImpact: 12,
    educationImpact: 20,
    crimeReduction: 3,
    landmarkPrestige: 18,
    upgradeLevels: generateDefaultUpgrades(2900000, 320, 340, 1),
    constructionTimeTicks: 90,
    spriteKey: 'ind_biotech_01',
    soundEffects: { build: 'sfx_build_glass', ambient: 'sfx_amb_bio_hum', action: 'sfx_centrifuge' }
  },
  vertical_farm: {
    id: 'vertical_farm',
    name: 'Hydroponic Vertical Farm',
    category: BUILDING_CATEGORIES.INDUSTRIAL,
    subcategory: BUILDING_SUBCATEGORIES.INDUSTRIAL_AGRICULTURE,
    size: [2, 3],
    cost: 380000,
    maintenanceCost: 1100,
    powerConsumption: 85,
    waterConsumption: -50,
    wasteProduction: 10,
    pollutionEmission: { air: -8, noise: 1, water: -5 },
    employeeCapacity: 45,
    residentialCapacity: 0,
    taxRevenueBase: 9800,
    happinessBonus: 12,
    serviceRadius: 6,
    healthImpact: 10,
    educationImpact: 4,
    crimeReduction: 1,
    landmarkPrestige: 8,
    upgradeLevels: generateDefaultUpgrades(380000, 45, 85, -8),
    constructionTimeTicks: 32,
    spriteKey: 'ind_vertfarm_01',
    soundEffects: { build: 'sfx_build_green', ambient: 'sfx_amb_misting', action: 'sfx_harvest_drone' }
  },
  logistics_hub: {
    id: 'logistics_hub',
    name: 'Automated Logistics Hub',
    category: BUILDING_CATEGORIES.INDUSTRIAL,
    subcategory: BUILDING_SUBCATEGORIES.INDUSTRIAL_WAREHOUSE,
    size: [4, 4],
    cost: 850000,
    maintenanceCost: 2800,
    powerConsumption: 120,
    waterConsumption: 30,
    wasteProduction: 110,
    pollutionEmission: { air: 8, noise: 10, water: 3 },
    employeeCapacity: 180,
    residentialCapacity: 0,
    taxRevenueBase: 26000,
    happinessBonus: 2,
    serviceRadius: 15,
    healthImpact: -2,
    educationImpact: 2,
    crimeReduction: 1,
    landmarkPrestige: 5,
    upgradeLevels: generateDefaultUpgrades(850000, 180, 120, 8),
    constructionTimeTicks: 50,
    spriteKey: 'ind_logistics_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_forklift', action: 'sfx_truck_horn' }
  },
  materials_recycling: {
    id: 'materials_recycling',
    name: 'Advanced Materials Recovery',
    category: BUILDING_CATEGORIES.INDUSTRIAL,
    subcategory: BUILDING_SUBCATEGORIES.INDUSTRIAL_RECYCLING,
    size: [3, 3],
    cost: 620000,
    maintenanceCost: 2100,
    powerConsumption: 95,
    waterConsumption: 60,
    wasteProduction: -300,
    pollutionEmission: { air: 4, noise: 12, water: 2 },
    employeeCapacity: 90,
    residentialCapacity: 0,
    taxRevenueBase: 14000,
    happinessBonus: 8,
    serviceRadius: 20,
    healthImpact: 5,
    educationImpact: 3,
    crimeReduction: 0,
    landmarkPrestige: 6,
    upgradeLevels: generateDefaultUpgrades(620000, 90, 95, 4),
    constructionTimeTicks: 40,
    spriteKey: 'ind_recycling_01',
    soundEffects: { build: 'sfx_build_heavy', ambient: 'sfx_amb_shredder', action: 'sfx_sorter_arm' }
  },

  // ---------------------------------------------------------------------------
  // 4. INFRASTRUCTURE CATEGORY
  // ---------------------------------------------------------------------------
  coal_power_plant: {
    id: 'coal_power_plant',
    name: 'Thermal Coal Power Plant',
    category: BUILDING_CATEGORIES.INFRASTRUCTURE,
    subcategory: BUILDING_SUBCATEGORIES.INFRASTRUCTURE_POWER,
    size: [4, 4],
    cost: 1500000,
    maintenanceCost: 6500,
    powerConsumption: -800,
    waterConsumption: 120,
    wasteProduction: 350,
    pollutionEmission: { air: 60, noise: 20, water: 25 },
    employeeCapacity: 120,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: -18,
    serviceRadius: 30,
    healthImpact: -15,
    educationImpact: 0,
    crimeReduction: 0,
    landmarkPrestige: 1,
    upgradeLevels: generateDefaultUpgrades(1500000, 120, -800, 60),
    constructionTimeTicks: 60,
    spriteKey: 'inf_power_coal_01',
    soundEffects: { build: 'sfx_build_heavy', ambient: 'sfx_amb_smokestack', action: 'sfx_coal_chute' }
  },
  gas_power_plant: {
    id: 'gas_power_plant',
    name: 'Combined Cycle Gas Plant',
    category: BUILDING_CATEGORIES.INFRASTRUCTURE,
    subcategory: BUILDING_SUBCATEGORIES.INFRASTRUCTURE_POWER,
    size: [3, 3],
    cost: 2200000,
    maintenanceCost: 7800,
    powerConsumption: -1200,
    waterConsumption: 80,
    wasteProduction: 90,
    pollutionEmission: { air: 20, noise: 12, water: 8 },
    employeeCapacity: 80,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: -8,
    serviceRadius: 35,
    healthImpact: -5,
    educationImpact: 1,
    crimeReduction: 0,
    landmarkPrestige: 3,
    upgradeLevels: generateDefaultUpgrades(2200000, 80, -1200, 20),
    constructionTimeTicks: 70,
    spriteKey: 'inf_power_gas_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_turbine_hum', action: 'sfx_gas_ignite' }
  },
  nuclear_power_plant: {
    id: 'nuclear_power_plant',
    name: 'Gen-IV Nuclear Reactor',
    category: BUILDING_CATEGORIES.INFRASTRUCTURE,
    subcategory: BUILDING_SUBCATEGORIES.INFRASTRUCTURE_POWER,
    size: [5, 5],
    cost: 9500000,
    maintenanceCost: 28000,
    powerConsumption: -5000,
    waterConsumption: 500,
    wasteProduction: 40,
    pollutionEmission: { air: 0, noise: 4, water: 5 },
    employeeCapacity: 350,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: -10,
    serviceRadius: 60,
    healthImpact: 0,
    educationImpact: 10,
    crimeReduction: 5,
    landmarkPrestige: 15,
    upgradeLevels: generateDefaultUpgrades(9500000, 350, -5000, 0),
    constructionTimeTicks: 160,
    spriteKey: 'inf_power_nuclear_01',
    soundEffects: { build: 'sfx_build_mega', ambient: 'sfx_amb_cooling_tower', action: 'sfx_geiger_counter' }
  },
  fusion_power_plant: {
    id: 'fusion_power_plant',
    name: 'Tokamak Fusion Plant',
    category: BUILDING_CATEGORIES.INFRASTRUCTURE,
    subcategory: BUILDING_SUBCATEGORIES.INFRASTRUCTURE_POWER,
    size: [6, 6],
    cost: 25000000,
    maintenanceCost: 60000,
    powerConsumption: -18000,
    waterConsumption: 250,
    wasteProduction: 0,
    pollutionEmission: { air: 0, noise: 1, water: 0 },
    employeeCapacity: 500,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 25,
    serviceRadius: 100,
    healthImpact: 10,
    educationImpact: 25,
    crimeReduction: 5,
    landmarkPrestige: 40,
    upgradeLevels: generateDefaultUpgrades(25000000, 500, -18000, 0),
    constructionTimeTicks: 250,
    spriteKey: 'inf_power_fusion_01',
    soundEffects: { build: 'sfx_build_futuristic', ambient: 'sfx_amb_plasma_hum', action: 'sfx_fusion_pulse' }
  },
  water_pumping_station: {
    id: 'water_pumping_station',
    name: 'River Water Pumping Station',
    category: BUILDING_CATEGORIES.INFRASTRUCTURE,
    subcategory: BUILDING_SUBCATEGORIES.INFRASTRUCTURE_WATER,
    size: [2, 2],
    cost: 180000,
    maintenanceCost: 600,
    powerConsumption: 30,
    waterConsumption: -1000,
    wasteProduction: 10,
    pollutionEmission: { air: 1, noise: 6, water: 5 },
    employeeCapacity: 15,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 2,
    serviceRadius: 25,
    healthImpact: 2,
    educationImpact: 0,
    crimeReduction: 0,
    landmarkPrestige: 1,
    upgradeLevels: generateDefaultUpgrades(180000, 15, 30, 1),
    constructionTimeTicks: 16,
    spriteKey: 'inf_water_pump_01',
    soundEffects: { build: 'sfx_build_pipe', ambient: 'sfx_amb_water_pump', action: 'sfx_valve_turn' }
  },
  water_treatment_plant: {
    id: 'water_treatment_plant',
    name: 'Municipal Water Purification Plant',
    category: BUILDING_CATEGORIES.INFRASTRUCTURE,
    subcategory: BUILDING_SUBCATEGORIES.INFRASTRUCTURE_WATER,
    size: [4, 3],
    cost: 850000,
    maintenanceCost: 2900,
    powerConsumption: 90,
    waterConsumption: -3500,
    wasteProduction: 60,
    pollutionEmission: { air: 2, noise: 5, water: -20 },
    employeeCapacity: 60,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 10,
    serviceRadius: 45,
    healthImpact: 15,
    educationImpact: 2,
    crimeReduction: 0,
    landmarkPrestige: 5,
    upgradeLevels: generateDefaultUpgrades(850000, 60, 90, 2),
    constructionTimeTicks: 45,
    spriteKey: 'inf_water_treatment_01',
    soundEffects: { build: 'sfx_build_concrete', ambient: 'sfx_amb_water_flow', action: 'sfx_filter_flush' }
  },
  desalination_plant: {
    id: 'desalination_plant',
    name: 'Reverse Osmosis Desalination Plant',
    category: BUILDING_CATEGORIES.INFRASTRUCTURE,
    subcategory: BUILDING_SUBCATEGORIES.INFRASTRUCTURE_WATER,
    size: [4, 4],
    cost: 3200000,
    maintenanceCost: 9800,
    powerConsumption: 380,
    waterConsumption: -8000,
    wasteProduction: 150,
    pollutionEmission: { air: 5, noise: 8, water: 15 },
    employeeCapacity: 110,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 12,
    serviceRadius: 70,
    healthImpact: 12,
    educationImpact: 3,
    crimeReduction: 0,
    landmarkPrestige: 10,
    upgradeLevels: generateDefaultUpgrades(3200000, 110, 380, 5),
    constructionTimeTicks: 85,
    spriteKey: 'inf_desalination_01',
    soundEffects: { build: 'sfx_build_heavy', ambient: 'sfx_amb_high_pressure', action: 'sfx_brine_discharge' }
  },
  sewage_treatment: {
    id: 'sewage_treatment',
    name: 'Central Sewage Treatment Facility',
    category: BUILDING_CATEGORIES.INFRASTRUCTURE,
    subcategory: BUILDING_SUBCATEGORIES.INFRASTRUCTURE_SEWAGE,
    size: [4, 4],
    cost: 950000,
    maintenanceCost: 3200,
    powerConsumption: 110,
    waterConsumption: 40,
    wasteProduction: -1200,
    pollutionEmission: { air: 12, noise: 8, water: -15 },
    employeeCapacity: 75,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 5,
    serviceRadius: 50,
    healthImpact: 18,
    educationImpact: 1,
    crimeReduction: 0,
    landmarkPrestige: 2,
    upgradeLevels: generateDefaultUpgrades(950000, 75, 110, 12),
    constructionTimeTicks: 48,
    spriteKey: 'inf_sewage_01',
    soundEffects: { build: 'sfx_build_concrete', ambient: 'sfx_amb_sludge_pump', action: 'sfx_aerator_splash' }
  },
  telecom_5g_relay: {
    id: 'telecom_5g_relay',
    name: '5G Smart Grid Relay Tower',
    category: BUILDING_CATEGORIES.INFRASTRUCTURE,
    subcategory: BUILDING_SUBCATEGORIES.INFRASTRUCTURE_TELECOM,
    size: [1, 1],
    cost: 45000,
    maintenanceCost: 220,
    powerConsumption: 15,
    waterConsumption: 0,
    wasteProduction: 1,
    pollutionEmission: { air: 0, noise: 1, water: 0 },
    employeeCapacity: 2,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 8,
    serviceRadius: 20,
    healthImpact: 0,
    educationImpact: 5,
    crimeReduction: 2,
    landmarkPrestige: 3,
    upgradeLevels: generateDefaultUpgrades(45000, 2, 15, 0),
    constructionTimeTicks: 8,
    spriteKey: 'inf_telecom_5g_01',
    soundEffects: { build: 'sfx_build_metal', ambient: 'sfx_amb_antenna_signal', action: 'sfx_ping_beep' }
  },
  waste_incinerator: {
    id: 'waste_incinerator',
    name: 'Waste-to-Energy Incinerator',
    category: BUILDING_CATEGORIES.INFRASTRUCTURE,
    subcategory: BUILDING_SUBCATEGORIES.INFRASTRUCTURE_WASTE,
    size: [3, 3],
    cost: 1100000,
    maintenanceCost: 3800,
    powerConsumption: -150,
    waterConsumption: 50,
    wasteProduction: -800,
    pollutionEmission: { air: 25, noise: 10, water: 8 },
    employeeCapacity: 65,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: -10,
    serviceRadius: 35,
    healthImpact: -6,
    educationImpact: 1,
    crimeReduction: 0,
    landmarkPrestige: 2,
    upgradeLevels: generateDefaultUpgrades(1100000, 65, -150, 25),
    constructionTimeTicks: 55,
    spriteKey: 'inf_waste_incinerator_01',
    soundEffects: { build: 'sfx_build_heavy', ambient: 'sfx_amb_furnace_roar', action: 'sfx_garbage_crush' }
  },

  // ---------------------------------------------------------------------------
  // 5. TRANSPORT CATEGORY
  // ---------------------------------------------------------------------------
  bus_depot: {
    id: 'bus_depot',
    name: 'Central Bus Terminal & Depot',
    category: BUILDING_CATEGORIES.TRANSPORT,
    subcategory: BUILDING_SUBCATEGORIES.TRANSPORT_BUS,
    size: [3, 3],
    cost: 240000,
    maintenanceCost: 950,
    powerConsumption: 25,
    waterConsumption: 15,
    wasteProduction: 30,
    pollutionEmission: { air: 8, noise: 12, water: 2 },
    employeeCapacity: 60,
    residentialCapacity: 0,
    taxRevenueBase: 1200,
    happinessBonus: 10,
    serviceRadius: 25,
    healthImpact: 1,
    educationImpact: 2,
    crimeReduction: 1,
    landmarkPrestige: 4,
    upgradeLevels: generateDefaultUpgrades(240000, 60, 25, 8),
    constructionTimeTicks: 24,
    spriteKey: 'trn_bus_depot_01',
    soundEffects: { build: 'sfx_build_asphalt', ambient: 'sfx_amb_bus_idle', action: 'sfx_bus_horn' }
  },
  subway_station: {
    id: 'subway_station',
    name: 'Underground Metro Hub',
    category: BUILDING_CATEGORIES.TRANSPORT,
    subcategory: BUILDING_SUBCATEGORIES.TRANSPORT_SUBWAY,
    size: [2, 2],
    cost: 750000,
    maintenanceCost: 2800,
    powerConsumption: 85,
    waterConsumption: 20,
    wasteProduction: 40,
    pollutionEmission: { air: 0, noise: 3, water: 0 },
    employeeCapacity: 40,
    residentialCapacity: 0,
    taxRevenueBase: 4500,
    happinessBonus: 18,
    serviceRadius: 30,
    healthImpact: 4,
    educationImpact: 3,
    crimeReduction: 3,
    landmarkPrestige: 8,
    upgradeLevels: generateDefaultUpgrades(750000, 40, 85, 0),
    constructionTimeTicks: 50,
    spriteKey: 'trn_subway_01',
    soundEffects: { build: 'sfx_build_tunnel', ambient: 'sfx_amb_subway_rumble', action: 'sfx_subway_chime' }
  },
  central_train_station: {
    id: 'central_train_station',
    name: 'Grand Central Railway Terminal',
    category: BUILDING_CATEGORIES.TRANSPORT,
    subcategory: BUILDING_SUBCATEGORIES.TRANSPORT_TRAIN,
    size: [5, 4],
    cost: 2800000,
    maintenanceCost: 8500,
    powerConsumption: 220,
    waterConsumption: 80,
    wasteProduction: 180,
    pollutionEmission: { air: 5, noise: 15, water: 3 },
    employeeCapacity: 250,
    residentialCapacity: 0,
    taxRevenueBase: 32000,
    happinessBonus: 25,
    serviceRadius: 50,
    healthImpact: 5,
    educationImpact: 5,
    crimeReduction: 4,
    landmarkPrestige: 22,
    upgradeLevels: generateDefaultUpgrades(2800000, 250, 220, 5),
    constructionTimeTicks: 90,
    spriteKey: 'trn_train_station_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_train_announcement', action: 'sfx_train_whistle' }
  },
  international_airport: {
    id: 'international_airport',
    name: 'Metropolitan International Airport',
    category: BUILDING_CATEGORIES.TRANSPORT,
    subcategory: BUILDING_SUBCATEGORIES.TRANSPORT_AIRPORT,
    size: [8, 8],
    cost: 18000000,
    maintenanceCost: 55000,
    powerConsumption: 1400,
    waterConsumption: 600,
    wasteProduction: 1200,
    pollutionEmission: { air: 50, noise: 40, water: 15 },
    employeeCapacity: 2200,
    residentialCapacity: 0,
    taxRevenueBase: 480000,
    happinessBonus: 35,
    serviceRadius: 120,
    healthImpact: -5,
    educationImpact: 8,
    crimeReduction: 5,
    landmarkPrestige: 45,
    upgradeLevels: generateDefaultUpgrades(18000000, 2200, 1400, 50),
    constructionTimeTicks: 220,
    spriteKey: 'trn_airport_01',
    soundEffects: { build: 'sfx_build_mega', ambient: 'sfx_amb_jet_engine', action: 'sfx_plane_takeoff' }
  },
  container_seaport: {
    id: 'container_seaport',
    name: 'Deepwater Container Port',
    category: BUILDING_CATEGORIES.TRANSPORT,
    subcategory: BUILDING_SUBCATEGORIES.TRANSPORT_SEAPORT,
    size: [6, 6],
    cost: 9500000,
    maintenanceCost: 32000,
    powerConsumption: 850,
    waterConsumption: 350,
    wasteProduction: 850,
    pollutionEmission: { air: 35, noise: 25, water: 30 },
    employeeCapacity: 1200,
    residentialCapacity: 0,
    taxRevenueBase: 290000,
    happinessBonus: 15,
    serviceRadius: 80,
    healthImpact: -8,
    educationImpact: 4,
    crimeReduction: 2,
    landmarkPrestige: 25,
    upgradeLevels: generateDefaultUpgrades(9500000, 1200, 850, 35),
    constructionTimeTicks: 160,
    spriteKey: 'trn_seaport_01',
    soundEffects: { build: 'sfx_build_heavy', ambient: 'sfx_amb_ship_horn', action: 'sfx_crane_lift' }
  },
  parking_garage: {
    id: 'parking_garage',
    name: 'Multi-Story Automated Parking',
    category: BUILDING_CATEGORIES.TRANSPORT,
    subcategory: BUILDING_SUBCATEGORIES.TRANSPORT_PARKING,
    size: [2, 3],
    cost: 210000,
    maintenanceCost: 700,
    powerConsumption: 25,
    waterConsumption: 5,
    wasteProduction: 15,
    pollutionEmission: { air: 6, noise: 8, water: 2 },
    employeeCapacity: 15,
    residentialCapacity: 0,
    taxRevenueBase: 3500,
    happinessBonus: 8,
    serviceRadius: 10,
    healthImpact: 0,
    educationImpact: 0,
    crimeReduction: 2,
    landmarkPrestige: 3,
    upgradeLevels: generateDefaultUpgrades(210000, 15, 25, 6),
    constructionTimeTicks: 22,
    spriteKey: 'trn_parking_01',
    soundEffects: { build: 'sfx_build_concrete', ambient: 'sfx_amb_car_alarm', action: 'sfx_gate_arm' }
  },

  // ---------------------------------------------------------------------------
  // 6. PUBLIC SERVICES CATEGORY
  // ---------------------------------------------------------------------------
  police_station: {
    id: 'police_station',
    name: 'Neighborhood Police Precinct',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_POLICE,
    size: [2, 2],
    cost: 220000,
    maintenanceCost: 950,
    powerConsumption: 20,
    waterConsumption: 10,
    wasteProduction: 20,
    pollutionEmission: { air: 1, noise: 4, water: 0 },
    employeeCapacity: 35,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 8,
    serviceRadius: 15,
    healthImpact: 2,
    educationImpact: 1,
    crimeReduction: 35,
    landmarkPrestige: 5,
    upgradeLevels: generateDefaultUpgrades(220000, 35, 20, 1),
    constructionTimeTicks: 20,
    spriteKey: 'pub_police_01',
    soundEffects: { build: 'sfx_build_brick', ambient: 'sfx_amb_police_radio', action: 'sfx_siren_wail' }
  },
  police_hq: {
    id: 'police_hq',
    name: 'Metropolitan Police Headquarters',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_POLICE,
    size: [4, 4],
    cost: 1800000,
    maintenanceCost: 6200,
    powerConsumption: 140,
    waterConsumption: 45,
    wasteProduction: 80,
    pollutionEmission: { air: 2, noise: 6, water: 1 },
    employeeCapacity: 280,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 18,
    serviceRadius: 40,
    healthImpact: 4,
    educationImpact: 4,
    crimeReduction: 85,
    landmarkPrestige: 18,
    upgradeLevels: generateDefaultUpgrades(1800000, 280, 140, 2),
    constructionTimeTicks: 65,
    spriteKey: 'pub_police_hq_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_dispatch', action: 'sfx_heli_blades' }
  },
  fire_station: {
    id: 'fire_station',
    name: 'District Fire Station',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_FIRE,
    size: [2, 2],
    cost: 190000,
    maintenanceCost: 850,
    powerConsumption: 18,
    waterConsumption: 25,
    wasteProduction: 15,
    pollutionEmission: { air: 1, noise: 5, water: 0 },
    employeeCapacity: 30,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 9,
    serviceRadius: 15,
    healthImpact: 4,
    educationImpact: 1,
    crimeReduction: 5,
    landmarkPrestige: 4,
    upgradeLevels: generateDefaultUpgrades(190000, 30, 18, 1),
    constructionTimeTicks: 18,
    spriteKey: 'pub_fire_01',
    soundEffects: { build: 'sfx_build_brick', ambient: 'sfx_amb_fire_radio', action: 'sfx_fire_horn' }
  },
  fire_hq: {
    id: 'fire_hq',
    name: 'Central Fire Response Command',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_FIRE,
    size: [3, 4],
    cost: 1400000,
    maintenanceCost: 5100,
    powerConsumption: 110,
    waterConsumption: 90,
    wasteProduction: 60,
    pollutionEmission: { air: 2, noise: 8, water: 1 },
    employeeCapacity: 210,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 20,
    serviceRadius: 40,
    healthImpact: 8,
    educationImpact: 3,
    crimeReduction: 10,
    landmarkPrestige: 15,
    upgradeLevels: generateDefaultUpgrades(1400000, 210, 110, 2),
    constructionTimeTicks: 55,
    spriteKey: 'pub_fire_hq_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_siren_distant', action: 'sfx_water_cannon' }
  },
  community_clinic: {
    id: 'community_clinic',
    name: 'Community Medical Clinic',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_HEALTH,
    size: [2, 2],
    cost: 150000,
    maintenanceCost: 700,
    powerConsumption: 22,
    waterConsumption: 18,
    wasteProduction: 25,
    pollutionEmission: { air: 0, noise: 2, water: 2 },
    employeeCapacity: 25,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 12,
    serviceRadius: 10,
    healthImpact: 25,
    educationImpact: 2,
    crimeReduction: 1,
    landmarkPrestige: 3,
    upgradeLevels: generateDefaultUpgrades(150000, 25, 22, 0),
    constructionTimeTicks: 16,
    spriteKey: 'pub_clinic_01',
    soundEffects: { build: 'sfx_build_brick', ambient: 'sfx_amb_heartbeat', action: 'sfx_ambulance_chime' }
  },
  general_hospital: {
    id: 'general_hospital',
    name: 'St. Jude General Hospital',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_HEALTH,
    size: [4, 4],
    cost: 2100000,
    maintenanceCost: 7500,
    powerConsumption: 190,
    waterConsumption: 130,
    wasteProduction: 180,
    pollutionEmission: { air: 1, noise: 4, water: 8 },
    employeeCapacity: 350,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 28,
    serviceRadius: 35,
    healthImpact: 65,
    educationImpact: 8,
    crimeReduction: 3,
    landmarkPrestige: 16,
    upgradeLevels: generateDefaultUpgrades(2100000, 350, 190, 1),
    constructionTimeTicks: 70,
    spriteKey: 'pub_hospital_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_intercom', action: 'sfx_life_monitor' }
  },
  medical_center_hq: {
    id: 'medical_center_hq',
    name: 'Advanced University Medical Center',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_HEALTH,
    size: [5, 5],
    cost: 5800000,
    maintenanceCost: 19000,
    powerConsumption: 480,
    waterConsumption: 320,
    wasteProduction: 400,
    pollutionEmission: { air: 2, noise: 5, water: 12 },
    employeeCapacity: 850,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 40,
    serviceRadius: 60,
    healthImpact: 100,
    educationImpact: 15,
    crimeReduction: 5,
    landmarkPrestige: 30,
    upgradeLevels: generateDefaultUpgrades(5800000, 850, 480, 2),
    constructionTimeTicks: 130,
    spriteKey: 'pub_medical_hq_01',
    soundEffects: { build: 'sfx_build_futuristic', ambient: 'sfx_amb_mri_hum', action: 'sfx_defibrillator' }
  },
  primary_school: {
    id: 'primary_school',
    name: 'Oakridge Primary School',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_EDUCATION,
    size: [3, 2],
    cost: 250000,
    maintenanceCost: 900,
    powerConsumption: 25,
    waterConsumption: 20,
    wasteProduction: 35,
    pollutionEmission: { air: 0, noise: 6, water: 1 },
    employeeCapacity: 30,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 15,
    serviceRadius: 12,
    healthImpact: 3,
    educationImpact: 30,
    crimeReduction: 4,
    landmarkPrestige: 4,
    upgradeLevels: generateDefaultUpgrades(250000, 30, 25, 0),
    constructionTimeTicks: 22,
    spriteKey: 'pub_primary_school_01',
    soundEffects: { build: 'sfx_build_brick', ambient: 'sfx_amb_recess', action: 'sfx_school_bell' }
  },
  high_school: {
    id: 'high_school',
    name: 'Central High Academy',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_EDUCATION,
    size: [4, 3],
    cost: 650000,
    maintenanceCost: 2200,
    powerConsumption: 60,
    waterConsumption: 45,
    wasteProduction: 75,
    pollutionEmission: { air: 1, noise: 8, water: 2 },
    employeeCapacity: 80,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 20,
    serviceRadius: 22,
    healthImpact: 5,
    educationImpact: 55,
    crimeReduction: 8,
    landmarkPrestige: 8,
    upgradeLevels: generateDefaultUpgrades(650000, 80, 60, 1),
    constructionTimeTicks: 40,
    spriteKey: 'pub_high_school_01',
    soundEffects: { build: 'sfx_build_steel', ambient: 'sfx_amb_hallway', action: 'sfx_locker_slam' }
  },
  metropolitan_university: {
    id: 'metropolitan_university',
    name: 'Metropolitan Research University',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_EDUCATION,
    size: [6, 5],
    cost: 4200000,
    maintenanceCost: 14000,
    powerConsumption: 420,
    waterConsumption: 250,
    wasteProduction: 310,
    pollutionEmission: { air: 2, noise: 5, water: 3 },
    employeeCapacity: 520,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 35,
    serviceRadius: 50,
    healthImpact: 10,
    educationImpact: 100,
    crimeReduction: 12,
    landmarkPrestige: 28,
    upgradeLevels: generateDefaultUpgrades(4200000, 520, 420, 2),
    constructionTimeTicks: 110,
    spriteKey: 'pub_university_01',
    soundEffects: { build: 'sfx_build_mega', ambient: 'sfx_amb_quad_chatter', action: 'sfx_graduation_cheer' }
  },
  city_central_park: {
    id: 'city_central_park',
    name: 'Grand Central Park',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_RECREATION,
    size: [4, 4],
    cost: 450000,
    maintenanceCost: 1200,
    powerConsumption: 5,
    waterConsumption: 60,
    wasteProduction: 15,
    pollutionEmission: { air: -15, noise: -8, water: -10 },
    employeeCapacity: 15,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 30,
    serviceRadius: 25,
    healthImpact: 20,
    educationImpact: 5,
    crimeReduction: 5,
    landmarkPrestige: 15,
    upgradeLevels: generateDefaultUpgrades(450000, 15, 5, -15),
    constructionTimeTicks: 25,
    spriteKey: 'pub_park_01',
    soundEffects: { build: 'sfx_build_grass', ambient: 'sfx_amb_birds_chirping', action: 'sfx_fountain_flow' }
  },
  olympic_stadium: {
    id: 'olympic_stadium',
    name: 'National Olympic Stadium',
    category: BUILDING_CATEGORIES.PUBLIC_SERVICES,
    subcategory: BUILDING_SUBCATEGORIES.PUBLIC_RECREATION,
    size: [6, 6],
    cost: 8500000,
    maintenanceCost: 26000,
    powerConsumption: 850,
    waterConsumption: 500,
    wasteProduction: 900,
    pollutionEmission: { air: 8, noise: 35, water: 10 },
    employeeCapacity: 750,
    residentialCapacity: 0,
    taxRevenueBase: 120000,
    happinessBonus: 50,
    serviceRadius: 60,
    healthImpact: 15,
    educationImpact: 5,
    crimeReduction: 5,
    landmarkPrestige: 50,
    upgradeLevels: generateDefaultUpgrades(8500000, 750, 850, 8),
    constructionTimeTicks: 180,
    spriteKey: 'pub_stadium_01',
    soundEffects: { build: 'sfx_build_mega', ambient: 'sfx_amb_stadium_roar', action: 'sfx_stadium_horn' }
  },

  // ---------------------------------------------------------------------------
  // 7. ENVIRONMENT CATEGORY
  // ---------------------------------------------------------------------------
  solar_farm: {
    id: 'solar_farm',
    name: 'Photovoltaic Solar Array',
    category: BUILDING_CATEGORIES.ENVIRONMENT,
    subcategory: BUILDING_SUBCATEGORIES.ENVIRONMENT_CLEAN_ENERGY,
    size: [4, 4],
    cost: 950000,
    maintenanceCost: 1500,
    powerConsumption: -450,
    waterConsumption: 2,
    wasteProduction: 2,
    pollutionEmission: { air: 0, noise: 0, water: 0 },
    employeeCapacity: 10,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 12,
    serviceRadius: 25,
    healthImpact: 5,
    educationImpact: 4,
    crimeReduction: 0,
    landmarkPrestige: 8,
    upgradeLevels: generateDefaultUpgrades(950000, 10, -450, 0),
    constructionTimeTicks: 30,
    spriteKey: 'env_solar_01',
    soundEffects: { build: 'sfx_build_glass', ambient: 'sfx_amb_inverter_hum', action: 'sfx_panel_orient' }
  },
  wind_turbine_farm: {
    id: 'wind_turbine_farm',
    name: 'Offshore Wind Turbine Cluster',
    category: BUILDING_CATEGORIES.ENVIRONMENT,
    subcategory: BUILDING_SUBCATEGORIES.ENVIRONMENT_CLEAN_ENERGY,
    size: [3, 3],
    cost: 1100000,
    maintenanceCost: 1800,
    powerConsumption: -600,
    waterConsumption: 0,
    wasteProduction: 0,
    pollutionEmission: { air: 0, noise: 4, water: 0 },
    employeeCapacity: 8,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 10,
    serviceRadius: 30,
    healthImpact: 4,
    educationImpact: 3,
    crimeReduction: 0,
    landmarkPrestige: 10,
    upgradeLevels: generateDefaultUpgrades(1100000, 8, -600, 0),
    constructionTimeTicks: 35,
    spriteKey: 'env_wind_01',
    soundEffects: { build: 'sfx_build_metal', ambient: 'sfx_amb_wind_blade', action: 'sfx_blade_whoosh' }
  },
  forest_reserve: {
    id: 'forest_reserve',
    name: 'Protected Old-Growth Forest Reserve',
    category: BUILDING_CATEGORIES.ENVIRONMENT,
    subcategory: BUILDING_SUBCATEGORIES.ENVIRONMENT_CONSERVATION,
    size: [5, 5],
    cost: 300000,
    maintenanceCost: 600,
    powerConsumption: 0,
    waterConsumption: -20,
    wasteProduction: -50,
    pollutionEmission: { air: -40, noise: -15, water: -25 },
    employeeCapacity: 12,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 35,
    serviceRadius: 40,
    healthImpact: 25,
    educationImpact: 8,
    crimeReduction: 2,
    landmarkPrestige: 20,
    upgradeLevels: generateDefaultUpgrades(300000, 12, 0, -40),
    constructionTimeTicks: 10,
    spriteKey: 'env_forest_01',
    soundEffects: { build: 'sfx_build_plant', ambient: 'sfx_amb_forest_wind', action: 'sfx_bird_call' }
  },
  air_scrubber_tower: {
    id: 'air_scrubber_tower',
    name: 'Carbon Capture Air Scrubber Tower',
    category: BUILDING_CATEGORIES.ENVIRONMENT,
    subcategory: BUILDING_SUBCATEGORIES.ENVIRONMENT_PURIFICATION,
    size: [2, 2],
    cost: 1450000,
    maintenanceCost: 4500,
    powerConsumption: 120,
    waterConsumption: 30,
    wasteProduction: 40,
    pollutionEmission: { air: -100, noise: 5, water: -10 },
    employeeCapacity: 15,
    residentialCapacity: 0,
    taxRevenueBase: 0,
    happinessBonus: 20,
    serviceRadius: 35,
    healthImpact: 30,
    educationImpact: 6,
    crimeReduction: 0,
    landmarkPrestige: 12,
    upgradeLevels: generateDefaultUpgrades(1450000, 15, 120, -100),
    constructionTimeTicks: 45,
    spriteKey: 'env_air_scrubber_01',
    soundEffects: { build: 'sfx_build_futuristic', ambient: 'sfx_amb_vacuum_suction', action: 'sfx_filter_cycle' }
  }
});

// Helper utilities for Buildings Data
export function getBuildingById(id) {
  return BUILDINGS[id] || null;
}

export function getBuildingsByCategory(category) {
  return Object.values(BUILDINGS).filter(b => b.category === category);
}

export function getBuildingsBySubcategory(subcategory) {
  return Object.values(BUILDINGS).filter(b => b.subcategory === subcategory);
}

export function calculateBuildingStatsAtTier(buildingId, tierLevel = 1) {
  const building = BUILDINGS[buildingId];
  if (!building) return null;

  const targetTier = building.upgradeLevels.find(u => u.tier === tierLevel) || building.upgradeLevels[0];
  const mults = targetTier.statMultipliers;

  return {
    ...building,
    currentTier: tierLevel,
    tierName: targetTier.name,
    cost: building.cost + targetTier.cost,
    maintenanceCost: Math.round(building.maintenanceCost * mults.maintenance),
    employeeCapacity: Math.round(building.employeeCapacity * mults.capacity),
    residentialCapacity: Math.round(building.residentialCapacity * mults.capacity),
    powerConsumption: Math.round(building.powerConsumption * mults.power),
    pollutionEmission: {
      air: Math.round(building.pollutionEmission.air * mults.pollution),
      noise: Math.round(building.pollutionEmission.noise * mults.pollution),
      water: Math.round(building.pollutionEmission.water * mults.pollution)
    },
    efficiencyBonus: mults.efficiency,
    specialAbilities: targetTier.specialAbilities
  };
}

export default BUILDINGS;
