/**
 * CITYMIND Multi-Language Localization Dictionary
 * Internationalization (i18n) translation tables supporting 8 languages:
 * English (en), Spanish (es), French (fr), German (de), Japanese (ja), Chinese (zh), Portuguese (pt), Italian (it).
 */

export const LOCALIZATION = {
  en: {
    ui: {
      gameTitle: 'CITYMIND — AI-Driven Dynamic City Simulation',
      population: 'Population',
      treasury: 'Treasury',
      happiness: 'Happiness Index',
      unemployment: 'Unemployment Rate',
      pollution: 'Air & Smog Pollution',
      powerGrid: 'Power Grid Load',
      waterSupply: 'Water & Sewage Supply',
      pause: 'Pause Simulation',
      resume: 'Resume Simulation',
      speedNormal: '1x Normal Speed',
      speedFast: '2x Fast Speed',
      speedFaster: '4x Faster Speed',
      speedFastest: '8x Fastest Speed',
      buildMenu: 'Build Structures & Zones',
      inspectTool: 'Inspect & Select Entity',
      demolishTool: 'Demolish Building (-$500)',
      policyCenter: 'City Hall Policy Ordinances',
      economyDashboard: 'City Financials & Debt Market',
      advisor: 'CITYMIND AI Advisor',
      achievements: 'Achievements & Milestones',
      audioSettings: 'Web Audio Synthesizer',
      scenarioMode: 'Challenge Scenarios Portal',
      sandboxMode: 'Open Sandbox Mode',
    },
    categories: {
      residential: 'Residential Housing',
      commercial: 'Commercial Retail & Offices',
      industrial: 'Industrial & Manufacturing',
      infrastructure: 'Power, Water & Utilities',
      transport: 'Roads & Mass Transit',
      publicServices: 'Police, Fire, Health & Education',
      environment: 'Parks & Green Energy',
      landmarks: 'Prestige Wonders & Monuments',
    },
    advisorAlerts: {
      powerShortage: 'CRITICAL: Substation power demand exceeds supply capacity!',
      waterContamination: 'WARNING: Groundwater pollution detected near Sector 4 reservoir.',
      trafficGridlock: 'WARNING: Traffic congestion on Main Expressway exceeds 80%.',
      crimeSpike: 'CRITICAL: Uncontained theft and vandalism in South Industrial District.',
      budgetDeficit: 'WARNING: Monthly expenditures exceed municipal tax revenues!',
      epidemicOutbreak: 'CRITICAL: Influenza outbreak spreading in Highrise Apt 4B.',
      utopiaMilestone: 'SUCCESS: City happiness has reached 90%! Citizens are ecstatic.',
    },
    policies: {
      green_energy_incentive: 'Green Energy Tax Subsidy',
      free_public_transit: 'Free City Transit Ordinance',
      recycling_mandate: 'Mandatory Recycling Program',
      plastic_bag_ban: 'Single-Use Plastics Ban',
      carbon_tax_high: 'Industrial Carbon Tariff',
      progressive_income_tax: 'Progressive Income Bracket Law',
      small_biz_tax_break: 'Small Business Exemption',
      police_camera_network: 'Smart Surveillance Network',
      universal_basic_income: 'Universal Basic Income Pilot',
    },
  },
  es: {
    ui: {
      gameTitle: 'CITYMIND — Simulación Urbana Impulsada por IA',
      population: 'Población',
      treasury: 'Tesorería',
      happiness: 'Índice de Felicidad',
      unemployment: 'Tasa de Desempleo',
      pollution: 'Contaminación del Aire',
      powerGrid: 'Carga de Red Eléctrica',
      waterSupply: 'Suministro de Agua',
      pause: 'Pausar Simulación',
      resume: 'Reanudar Simulación',
      speedNormal: '1x Velocidad Normal',
      speedFast: '2x Rápido',
      speedFaster: '4x Más Rápido',
      speedFastest: '8x Máxima Velocidad',
      buildMenu: 'Construir Estructuras y Zonas',
      inspectTool: 'Inspeccionar Entidad',
      demolishTool: 'Demoler Edificio (-$500)',
      policyCenter: 'Ordenanzas del Ayuntamiento',
      economyDashboard: 'Finanzas y Mercado de Deuda',
      advisor: 'Asesor IA CITYMIND',
      achievements: 'Logros y Hitos',
      audioSettings: 'Sintetizador Web Audio',
      scenarioMode: 'Portal de Escenarios de Desafío',
      sandboxMode: 'Modo Sandbox Abierto',
    },
    categories: {
      residential: 'Vivienda Residencial',
      commercial: 'Comercio y Oficinas',
      industrial: 'Industria y Manufactura',
      infrastructure: 'Energía y Servicios',
      transport: 'Carreteras y Transporte',
      publicServices: 'Policía, Salud y Educación',
      environment: 'Parques y Energía Verde',
      landmarks: 'Maravillas y Monumentos',
    },
  },
  fr: {
    ui: {
      gameTitle: 'CITYMIND — Simulation Urbaine IA Dynamique',
      population: 'Population',
      treasury: 'Trésorerie',
      happiness: 'Indice de Bonheur',
      unemployment: 'Taux de Chômage',
      pollution: 'Pollution de l\'Air',
      powerGrid: 'Réseau Électrique',
      waterSupply: 'Approvisionnement en Eau',
      pause: 'Pause',
      resume: 'Reprendre',
      speedNormal: '1x Vitesse Normale',
      speedFast: '2x Vitesse Rapide',
      speedFaster: '4x Très Rapide',
      speedFastest: '8x Vitesse Maximale',
      buildMenu: 'Construire Structures & Zones',
      inspectTool: 'Inspecter Élément',
      demolishTool: 'Démolir Bâtiment (-500$)',
      policyCenter: 'Ordonnances Municipales',
      economyDashboard: 'Finances & Marché de la Dette',
      advisor: 'Conseiller IA CITYMIND',
      achievements: 'Succès & Étapes',
      audioSettings: 'Synthétiseur Web Audio',
      scenarioMode: 'Portail des Scénarios',
      sandboxMode: 'Mode Bac à Sable',
    },
  },
  de: {
    ui: {
      gameTitle: 'CITYMIND — KI-Gestützte Stadtsimulation',
      population: 'Bevölkerung',
      treasury: 'Stadtkasse',
      happiness: 'Zufriedenheitsindex',
      unemployment: 'Arbeitslosenquote',
      pollution: 'Luftverschmutzung',
      powerGrid: 'Stromnetz-Auslastung',
      waterSupply: 'Wasserversorgung',
      pause: 'Pause',
      resume: 'Fortsetzen',
      speedNormal: '1x Normale Geschwindigkeit',
      speedFast: '2x Schnell',
      speedFaster: '4x Sehr Schnell',
      speedFastest: '8x Maximale Geschwindigkeit',
      buildMenu: 'Gebäude & Zonen Bauen',
      inspectTool: 'Inspektionswerkzeug',
      demolishTool: 'Gebäude Abreißen (-500$)',
      policyCenter: 'Rathaus-Verordnungen',
      economyDashboard: 'Finanzen & Anleihenmarkt',
      advisor: 'CITYMIND KI-Berater',
      achievements: 'Erfolge & Meilensteine',
      audioSettings: 'Web-Audio-Synthesizer',
      scenarioMode: 'Szenario-Herausforderungen',
      sandboxMode: 'Freier Sandbox-Modus',
    },
  },
  ja: {
    ui: {
      gameTitle: 'CITYMIND — AI駆動型動的都市シミュレーション',
      population: '人口',
      treasury: '市財務庫',
      happiness: '市民幸福度',
      unemployment: '失業率',
      pollution: '大気汚染度',
      powerGrid: '電力網負荷',
      waterSupply: '水道供給量',
      pause: '一時停止',
      resume: '再開',
      speedNormal: '1倍 標準速度',
      speedFast: '2倍 高速',
      speedFaster: '4倍 超高速',
      speedFastest: '8倍 最高速',
      buildMenu: '建築・ゾーニング',
      inspectTool: '詳細調査ツール',
      demolishTool: '建物撤去 (-$500)',
      policyCenter: '市役所政策・条例',
      economyDashboard: '都市財務・債券市場',
      advisor: 'CITYMIND AIアドバイザー',
      achievements: '実績とマイルストーン',
      audioSettings: 'Web Audio シンセサイザー',
      scenarioMode: 'チャレンジシナリオ',
      sandboxMode: 'サンドボックスモード',
    },
  },
  zh: {
    ui: {
      gameTitle: 'CITYMIND — AI驱动的动态城市模拟平台',
      population: '城市人口',
      treasury: '市政金库',
      happiness: '市民幸福指数',
      unemployment: '失业率',
      pollution: '空气烟雾污染',
      powerGrid: '电网负载',
      waterSupply: '供水与供暖',
      pause: '暂停模拟',
      resume: '继续模拟',
      speedNormal: '1倍 标准速度',
      speedFast: '2倍 快速',
      speedFaster: '4倍 特快',
      speedFastest: '8倍 极速',
      buildMenu: '建筑与区域规划',
      inspectTool: '检查与选择工具',
      demolishTool: '拆除建筑物 (-$500)',
      policyCenter: '市政厅政策与法案',
      economyDashboard: '城市财政与债券市场',
      advisor: 'CITYMIND AI顾问',
      achievements: '成就与里程碑',
      audioSettings: 'Web Audio 音频合成器',
      scenarioMode: '挑战剧本关卡',
      sandboxMode: '自由沙盒模式',
    },
  },
};

export function getTranslation(lang, category, key) {
  const table = LOCALIZATION[lang] || LOCALIZATION.en;
  const catObj = table[category] || LOCALIZATION.en[category];
  if (!catObj) return key;
  return catObj[key] || LOCALIZATION.en[category]?.[key] || key;
}

export default LOCALIZATION;
