/**
 * CITYMIND Multi-Language Dictionary Data (Part 5)
 * Full translation tables for Italian (it), Portuguese (pt), Spanish (es), French (fr), German (de), Japanese (ja), Chinese (zh).
 */

export const MULTI_LANG_PART_5 = {
  it: {
    ui: {
      gameTitle: 'CITYMIND — Simulazione Urbana Guidata da IA',
      population: 'Popolazione',
      treasury: 'Tesoreria',
      happiness: 'Indice di Felicità',
      unemployment: 'Tasso di Disoccupazione',
      pollution: 'Inquinamento dell\'Aria',
      powerGrid: 'Rete Elettrica',
      waterSupply: 'Fornitura d\'Acqua',
      pause: 'Pausa',
      resume: 'Riprendi',
      speedNormal: '1x Velocità Normale',
      speedFast: '2x Veloce',
      speedFaster: '4x Molto Veloce',
      speedFastest: '8x Massima Velocità',
      buildMenu: 'Costruisci Strutture e Zone',
      inspectTool: 'Ispeziona Entità',
      demolishTool: 'Demolisci Edificio (-$500)',
      policyCenter: 'Ordinanze del Municipio',
      economyDashboard: 'Finanze & Mercato dei Titoli',
      advisor: 'Consigliere IA CITYMIND',
      achievements: 'Obiettivi & Traguardi',
      audioSettings: 'Sintetizzatore Web Audio',
      scenarioMode: 'Portale degli Scenario',
      sandboxMode: 'Modalità Sandbox',
    },
    categories: {
      residential: 'Alloggi Residenziali',
      commercial: 'Commercio e Uffici',
      industrial: 'Industria e Manifattura',
      infrastructure: 'Energia e Servizi Pubblici',
      transport: 'Strade e Trasporti Pubblici',
      publicServices: 'Polizia, Sanità e Istruzione',
      environment: 'Parchi ed Energia Verde',
      landmarks: 'Monumenti e Meraviglie',
    },
  },
  pt: {
    ui: {
      gameTitle: 'CITYMIND — Simulação Urbana Orientada por IA',
      population: 'População',
      treasury: 'Tesouraria',
      happiness: 'Índice de Felicidade',
      unemployment: 'Taxa de Desemprego',
      pollution: 'Poluição do Ar',
      powerGrid: 'Rede Elétrica',
      waterSupply: 'Abastecimento de Água',
      pause: 'Pausar',
      resume: 'Retomar',
      speedNormal: '1x Velocidade Normal',
      speedFast: '2x Rápido',
      speedFaster: '4x Muito Rápido',
      speedFastest: '8x Velocidade Máxima',
      buildMenu: 'Construir Estruturas e Zonas',
      inspectTool: 'Inspecionar Entidade',
      demolishTool: 'Demolir Edifício (-$500)',
      policyCenter: 'Decretos da Prefeitura',
      economyDashboard: 'Finanças e Mercado de Títulos',
      advisor: 'Conselheiro de IA CITYMIND',
      achievements: 'Conquistas e Marcos',
      audioSettings: 'Sintetizador Web Audio',
      scenarioMode: 'Portal de Cenários de Desafio',
      sandboxMode: 'Modo Sandbox',
    },
    categories: {
      residential: 'Habitação Residencial',
      commercial: 'Comércio e Escritórios',
      industrial: 'Indústria e Manufatura',
      infrastructure: 'Energia e Serviços Públicos',
      transport: 'Estradas e Transporte Público',
      publicServices: 'Polícia, Saúde e Educação',
      environment: 'Parques e Energia Verde',
      landmarks: 'Maravilhas e Monumentos',
    },
  },
};

export default MULTI_LANG_PART_5;
