/**
 * CITYMIND Internationalization Dictionary Extension (Part 4)
 * Comprehensive translation mappings for scenario objectives, economic policies,
 * advisor card diagnostics, demographic labels, and sound synthesizer settings.
 */

export const MULTI_LANG_EXTENSION = {
  en: {
    ui: {
      financials: 'City Financial & Economy Dashboard',
      treasuryBalance: 'Treasury Balance',
      monthlyIncome: 'Monthly Income Sources',
      monthlyExpenses: 'Monthly Expenditures',
      rciDemand: 'RCI Zoning Demand Indicators',
      residentialDemand: 'Residential Demand (R)',
      commercialDemand: 'Commercial Demand (C)',
      industrialDemand: 'Industrial Demand (I)',
      policiesCatalog: 'City Ordinances & Policy Catalog',
      enactLaw: 'Enact Law',
      repealLaw: 'Repeal Law',
      voterApproval: 'Voter Approval Rate',
      achievementsTitle: 'Achievements & City Milestones',
      completed: 'COMPLETED',
      locked: 'LOCKED',
    },
    advisorCards: {
      powerShortageTitle: 'Imminent Substation Power Overload',
      powerShortageRec: 'Construct a Solar Micro-Farm or Upgrade Substation 3 to Level 3.',
      trafficGridlockTitle: 'Severe Traffic Congestion on Arterial Avenues',
      trafficGridlockRec: 'Enact Free Public Transit Ordinance & Construct Bus Rapid Transit (BRT) Line 1.',
      crimeSurgeTitle: 'Rising Crime Rate in South Industrial District',
      crimeSurgeRec: 'Deploy Police Precinct Station & Enact Smart Camera Surveillance Network.',
      budgetCrisisTitle: 'Municipal Treasury Depletion Risk',
      budgetCrisisRec: 'Temporarily increase Commercial Tax by +2% or Issue a 5-Year Municipal Infrastructure Bond.',
    },
  },
  es: {
    ui: {
      financials: 'Panel de Finanzas y Economía Urbana',
      treasuryBalance: 'Balance de Tesorería',
      monthlyIncome: 'Fuentes de Ingresos Mensuales',
      monthlyExpenses: 'Gastos Mensuales',
      rciDemand: 'Indicadores de Demanda RCI',
      residentialDemand: 'Demanda Residencial (R)',
      commercialDemand: 'Demanda Comercial (C)',
      industrialDemand: 'Demanda Industrial (I)',
      policiesCatalog: 'Catálogo de Leyes y Ordenanzas',
      enactLaw: 'Promulgar Ley',
      repealLaw: 'Derogar Ley',
      voterApproval: 'Tasa de Aprobación de Votantes',
      achievementsTitle: 'Logros y Hitos Urbanos',
      completed: 'COMPLETADO',
      locked: 'BLOQUEADO',
    },
  },
  fr: {
    ui: {
      financials: 'Tableau de Bord Financier Municipal',
      treasuryBalance: 'Solde de la Trésorerie',
      monthlyIncome: 'Revenus Mensuels',
      monthlyExpenses: 'Dépenses Mensuelles',
      rciDemand: 'Indicateurs de Demande RCI',
      residentialDemand: 'Demande Résidentielle (R)',
      commercialDemand: 'Demande Commerciale (C)',
      industrialDemand: 'Demande Industrielle (I)',
      policiesCatalog: 'Catalogue des Ordonnances',
      enactLaw: 'Promulguer Loi',
      repealLaw: 'Abroger Loi',
      voterApproval: 'Taux d\'Approbation des Électeurs',
      achievementsTitle: 'Succès & Étapes',
      completed: 'TERMINÉ',
      locked: 'VERROUILLÉ',
    },
  },
  de: {
    ui: {
      financials: 'Finanz- und Wirtschafts-Dashboard',
      treasuryBalance: 'Kassenbestand',
      monthlyIncome: 'Monatliche Einnahmen',
      monthlyExpenses: 'Monatliche Ausgaben',
      rciDemand: 'RCI-Nachfrageindikatoren',
      residentialDemand: 'Wohnnachfrage (R)',
      commercialDemand: 'Gewerbenachfrage (C)',
      industrialDemand: 'Industrienachfrage (I)',
      policiesCatalog: 'Stadtverordnungs-Katalog',
      enactLaw: 'Gesetz Erlassen',
      repealLaw: 'Gesetz Aufheben',
      voterApproval: 'Wähler-Zustimmungsrate',
      achievementsTitle: 'Erfolge & Meilensteine',
      completed: 'ABGESCHLOSSEN',
      locked: 'GESPERRT',
    },
  },
  ja: {
    ui: {
      financials: '都市財務・経済ダッシュボード',
      treasuryBalance: '市金庫残高',
      monthlyIncome: '月間収入源',
      monthlyExpenses: '月間支出項目',
      rciDemand: 'RCIゾーニング需要指標',
      residentialDemand: '住宅需要 (R)',
      commercialDemand: '商業需要 (C)',
      industrialDemand: '工业需要 (I)',
      policiesCatalog: '市条例・政策カタログ',
      enactLaw: '条例制定',
      repealLaw: '条例撤廃',
      voterApproval: '有権者支持率',
      achievementsTitle: '実績とマイルストーン',
      completed: '達成済み',
      locked: '未解放',
    },
  },
  zh: {
    ui: {
      financials: '城市财政与经济仪表盘',
      treasuryBalance: '金库余额',
      monthlyIncome: '月度收入来源',
      monthlyExpenses: '月度支出项目',
      rciDemand: 'RCI规划需求指标',
      residentialDemand: '住宅需求 (R)',
      commercialDemand: '商业需求 (C)',
      industrialDemand: '工业需求 (I)',
      policiesCatalog: '城市法案与政策目录',
      enactLaw: '颁布法案',
      repealLaw: '废除法案',
      voterApproval: '选民支持率',
      achievementsTitle: '成就与里程碑',
      completed: '已完成',
      locked: '未解锁',
    },
  },
};

export default MULTI_LANG_EXTENSION;
