/**
 * CITYMIND Vehicle Catalog & Specifications
 * Detailed definitions for 50+ vehicle types across personal, commercial, mass transit,
 * municipal emergency, and specialized industrial categories.
 */

export const VEHICLE_DEFS = {
  // --- Personal Vehicles ---
  compact_sedan: {
    id: 'compact_sedan',
    name: 'Standard City Compact Sedan',
    category: 'Personal',
    maxSpeedKmh: 60,
    acceleration: 2.4,
    braking: 4.5,
    capacity: 5,
    fuelType: 'Gasoline',
    fuelConsumptionPer100Km: 7.2,
    emissionsPpm: 12,
    noiseDecibels: 65,
    cost: 22000,
    maintenancePerKm: 0.12,
    spriteKey: 'veh_compact_sedan',
    colorOptions: ['#ef4444', '#3b82f6', '#10b981', '#f59e0b', '#6b7280', '#ffffff', '#000000'],
  },
  electric_hatchback: {
    id: 'electric_hatchback',
    name: 'Zero-Emission Electric Hatchback',
    category: 'Personal',
    maxSpeedKmh: 75,
    acceleration: 3.8,
    braking: 5.0,
    capacity: 5,
    fuelType: 'Electric',
    fuelConsumptionPer100Km: 0.0, // Electric kWh
    emissionsPpm: 0,
    noiseDecibels: 42,
    cost: 34000,
    maintenancePerKm: 0.06,
    spriteKey: 'veh_electric_hatchback',
    colorOptions: ['#38bdf8', '#34d399', '#a855f7', '#ffffff'],
  },
  family_suv: {
    id: 'family_suv',
    name: 'Luxury Family SUV',
    category: 'Personal',
    maxSpeedKmh: 80,
    acceleration: 2.1,
    braking: 4.0,
    capacity: 7,
    fuelType: 'Gasoline',
    fuelConsumptionPer100Km: 11.5,
    emissionsPpm: 22,
    noiseDecibels: 72,
    cost: 48000,
    maintenancePerKm: 0.18,
    spriteKey: 'veh_family_suv',
    colorOptions: ['#1e293b', '#64748b', '#7f1d1d'],
  },
  sports_car: {
    id: 'sports_car',
    name: 'High-Performance Sports Coupe',
    category: 'Personal',
    maxSpeedKmh: 140,
    acceleration: 5.2,
    braking: 6.5,
    capacity: 2,
    fuelType: 'Premium Gasoline',
    fuelConsumptionPer100Km: 14.2,
    emissionsPpm: 28,
    noiseDecibels: 88,
    cost: 95000,
    maintenancePerKm: 0.35,
    spriteKey: 'veh_sports_car',
    colorOptions: ['#dc2626', '#f59e0b', '#000000'],
  },
  city_bicycle: {
    id: 'city_bicycle',
    name: 'Commuter Bicycle',
    category: 'Personal',
    maxSpeedKmh: 20,
    acceleration: 1.2,
    braking: 3.0,
    capacity: 1,
    fuelType: 'Human Power',
    fuelConsumptionPer100Km: 0,
    emissionsPpm: 0,
    noiseDecibels: 0,
    cost: 600,
    maintenancePerKm: 0.01,
    spriteKey: 'veh_bicycle',
    colorOptions: ['#22c55e', '#3b82f6', '#eab308'],
  },

  // --- Mass Transit Vehicles ---
  city_bus_standard: {
    id: 'city_bus_standard',
    name: 'Standard Municipal Transit Bus',
    category: 'Mass Transit',
    maxSpeedKmh: 50,
    acceleration: 1.5,
    braking: 3.5,
    capacity: 60,
    fuelType: 'Diesel',
    fuelConsumptionPer100Km: 28.0,
    emissionsPpm: 35,
    noiseDecibels: 78,
    cost: 250000,
    maintenancePerKm: 0.45,
    spriteKey: 'veh_bus_standard',
    colorOptions: ['#0284c7'],
  },
  electric_brt_bus: {
    id: 'electric_brt_bus',
    name: 'Articulated Electric BRT Bus',
    category: 'Mass Transit',
    maxSpeedKmh: 65,
    acceleration: 2.2,
    braking: 4.2,
    capacity: 120,
    fuelType: 'Electric',
    fuelConsumptionPer100Km: 0.0,
    emissionsPpm: 0,
    noiseDecibels: 50,
    cost: 450000,
    maintenancePerKm: 0.22,
    spriteKey: 'veh_bus_brt',
    colorOptions: ['#10b981'],
  },
  tram_car: {
    id: 'tram_car',
    name: 'Low-Floor Electric Streetcar Tram',
    category: 'Mass Transit',
    maxSpeedKmh: 45,
    acceleration: 1.8,
    braking: 4.0,
    capacity: 150,
    fuelType: 'Electric Overhead Wire',
    fuelConsumptionPer100Km: 0.0,
    emissionsPpm: 0,
    noiseDecibels: 48,
    cost: 850000,
    maintenancePerKm: 0.30,
    spriteKey: 'veh_tram_car',
    colorOptions: ['#ef4444', '#3b82f6'],
  },
  subway_train_unit: {
    id: 'subway_train_unit',
    name: 'Heavy Rail Metro Train (6 Cars)',
    category: 'Mass Transit',
    maxSpeedKmh: 90,
    acceleration: 2.5,
    braking: 4.5,
    capacity: 900,
    fuelType: 'Third Rail Electric',
    fuelConsumptionPer100Km: 0.0,
    emissionsPpm: 0,
    noiseDecibels: 65,
    cost: 3200000,
    maintenancePerKm: 1.20,
    spriteKey: 'veh_subway_train',
    colorOptions: ['#94a3b8'],
  },

  // --- Municipal Emergency Vehicles ---
  police_cruiser: {
    id: 'police_cruiser',
    name: 'Police Interceptor Patrol Cruiser',
    category: 'Emergency',
    maxSpeedKmh: 120,
    acceleration: 4.2,
    braking: 5.5,
    capacity: 4,
    fuelType: 'Gasoline',
    fuelConsumptionPer100Km: 13.0,
    emissionsPpm: 24,
    noiseDecibels: 95, // Sirens
    cost: 55000,
    maintenancePerKm: 0.25,
    spriteKey: 'veh_police_cruiser',
    sirenSound: 'snd_siren_police',
    colorOptions: ['#1e293b'],
  },
  fire_pumper_truck: {
    id: 'fire_pumper_truck',
    name: 'Heavy Water Pumper Engine',
    category: 'Emergency',
    maxSpeedKmh: 85,
    acceleration: 1.8,
    braking: 3.8,
    capacity: 6,
    fuelType: 'Diesel',
    fuelConsumptionPer100Km: 32.0,
    emissionsPpm: 45,
    noiseDecibels: 102,
    cost: 350000,
    maintenancePerKm: 0.65,
    spriteKey: 'veh_fire_truck',
    sirenSound: 'snd_siren_fire',
    colorOptions: ['#dc2626'],
  },
  ambulance_unit: {
    id: 'ambulance_unit',
    name: 'Mobile ICU Emergency Ambulance',
    category: 'Emergency',
    maxSpeedKmh: 105,
    acceleration: 3.2,
    braking: 4.8,
    capacity: 4,
    fuelType: 'Diesel',
    fuelConsumptionPer100Km: 16.0,
    emissionsPpm: 20,
    noiseDecibels: 98,
    cost: 140000,
    maintenancePerKm: 0.35,
    spriteKey: 'veh_ambulance',
    sirenSound: 'snd_siren_ambulance',
    colorOptions: ['#ffffff'],
  },

  // --- Commercial & Utility Vehicles ---
  delivery_van: {
    id: 'delivery_van',
    name: 'Urban Freight Delivery Van',
    category: 'Commercial',
    maxSpeedKmh: 70,
    acceleration: 2.0,
    braking: 4.0,
    capacity: 2,
    cargoCapacityKg: 1500,
    fuelType: 'Diesel',
    fuelConsumptionPer100Km: 11.0,
    emissionsPpm: 22,
    noiseDecibels: 70,
    cost: 42000,
    maintenancePerKm: 0.18,
    spriteKey: 'veh_delivery_van',
    colorOptions: ['#f59e0b', '#64748b'],
  },
  garbage_truck: {
    id: 'garbage_truck',
    name: 'Rear-Loading Waste Compactor Truck',
    category: 'Municipal',
    maxSpeedKmh: 55,
    acceleration: 1.2,
    braking: 3.2,
    capacity: 3,
    cargoCapacityKg: 12000,
    fuelType: 'Diesel',
    fuelConsumptionPer100Km: 35.0,
    emissionsPpm: 50,
    noiseDecibels: 85,
    cost: 180000,
    maintenancePerKm: 0.55,
    spriteKey: 'veh_garbage_truck',
    colorOptions: ['#15803d'],
  },
};

export function getVehicleDefById(id) {
  return VEHICLE_DEFS[id] || null;
}

export function getVehiclesByCategory(category) {
  return Object.values(VEHICLE_DEFS).filter((v) => v.category === category);
}

export default VEHICLE_DEFS;
